package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_bm_login", Class = PanoBmLogin.class)
public class PanoBmLogin<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.LOGIN_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String loginName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.PASSWORD
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.STATUS
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.USER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long userSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.LOGIN_TIMES
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Integer loginTimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.SUMMARY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String summary;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Date lastLoginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_login.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.SN
     *
     * @return the value of pano_bm_login.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.SN
     *
     * @param sn the value for pano_bm_login.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.LOGIN_NAME
     *
     * @return the value of pano_bm_login.LOGIN_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.LOGIN_NAME
     *
     * @param loginName the value for pano_bm_login.LOGIN_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.PASSWORD
     *
     * @return the value of pano_bm_login.PASSWORD
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.PASSWORD
     *
     * @param password the value for pano_bm_login.PASSWORD
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.STATUS
     *
     * @return the value of pano_bm_login.STATUS
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.STATUS
     *
     * @param status the value for pano_bm_login.STATUS
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.USER_SN
     *
     * @return the value of pano_bm_login.USER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.USER_SN
     *
     * @param userSn the value for pano_bm_login.USER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUserSn(Long userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.LOGIN_TIMES
     *
     * @return the value of pano_bm_login.LOGIN_TIMES
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.LOGIN_TIMES
     *
     * @param loginTimes the value for pano_bm_login.LOGIN_TIMES
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.SUMMARY
     *
     * @return the value of pano_bm_login.SUMMARY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.SUMMARY
     *
     * @param summary the value for pano_bm_login.SUMMARY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.LAST_LOGIN_TIME
     *
     * @return the value of pano_bm_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for pano_bm_login.LAST_LOGIN_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.ADDER_SN
     *
     * @return the value of pano_bm_login.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.ADDER_SN
     *
     * @param adderSn the value for pano_bm_login.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.ADDER_NAME
     *
     * @return the value of pano_bm_login.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.ADDER_NAME
     *
     * @param adderName the value for pano_bm_login.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.ADD_TIME
     *
     * @return the value of pano_bm_login.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.ADD_TIME
     *
     * @param addTime the value for pano_bm_login.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.UPDATER_SN
     *
     * @return the value of pano_bm_login.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.UPDATER_SN
     *
     * @param updaterSn the value for pano_bm_login.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.UPDATER_NAME
     *
     * @return the value of pano_bm_login.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.UPDATER_NAME
     *
     * @param updaterName the value for pano_bm_login.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.UPDATE_TIME
     *
     * @return the value of pano_bm_login.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.UPDATE_TIME
     *
     * @param updateTime the value for pano_bm_login.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_login.encryptSn
     *
     * @return the value of pano_bm_login.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_login.encryptSn
     *
     * @param encryptSn the value for pano_bm_login.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}