package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_validate", Class = PanoValidate.class)
public class PanoValidate<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.SEND_OBJ
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String sendObj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.CODE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.EXPIRE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Integer expire;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.STATUS
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.IP_ADDR
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String ipAddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.IP_POSITION
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String ipPosition;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.CREATE_DATE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_validate.encryptSn
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.SN
     *
     * @return the value of pano_validate.SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.SN
     *
     * @param sn the value for pano_validate.SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.SEND_OBJ
     *
     * @return the value of pano_validate.SEND_OBJ
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getSendObj() {
        return sendObj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.SEND_OBJ
     *
     * @param sendObj the value for pano_validate.SEND_OBJ
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setSendObj(String sendObj) {
        this.sendObj = sendObj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.CODE
     *
     * @return the value of pano_validate.CODE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.CODE
     *
     * @param code the value for pano_validate.CODE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.EXPIRE
     *
     * @return the value of pano_validate.EXPIRE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.EXPIRE
     *
     * @param expire the value for pano_validate.EXPIRE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.STATUS
     *
     * @return the value of pano_validate.STATUS
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.STATUS
     *
     * @param status the value for pano_validate.STATUS
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.IP_ADDR
     *
     * @return the value of pano_validate.IP_ADDR
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.IP_ADDR
     *
     * @param ipAddr the value for pano_validate.IP_ADDR
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.IP_POSITION
     *
     * @return the value of pano_validate.IP_POSITION
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getIpPosition() {
        return ipPosition;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.IP_POSITION
     *
     * @param ipPosition the value for pano_validate.IP_POSITION
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setIpPosition(String ipPosition) {
        this.ipPosition = ipPosition;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.CREATE_DATE
     *
     * @return the value of pano_validate.CREATE_DATE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.CREATE_DATE
     *
     * @param createDate the value for pano_validate.CREATE_DATE
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.ADDER_SN
     *
     * @return the value of pano_validate.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.ADDER_SN
     *
     * @param adderSn the value for pano_validate.ADDER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.ADDER_NAME
     *
     * @return the value of pano_validate.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.ADDER_NAME
     *
     * @param adderName the value for pano_validate.ADDER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.ADD_TIME
     *
     * @return the value of pano_validate.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.ADD_TIME
     *
     * @param addTime the value for pano_validate.ADD_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.UPDATER_SN
     *
     * @return the value of pano_validate.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.UPDATER_SN
     *
     * @param updaterSn the value for pano_validate.UPDATER_SN
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.UPDATER_NAME
     *
     * @return the value of pano_validate.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.UPDATER_NAME
     *
     * @param updaterName the value for pano_validate.UPDATER_NAME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.UPDATE_TIME
     *
     * @return the value of pano_validate.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.UPDATE_TIME
     *
     * @param updateTime the value for pano_validate.UPDATE_TIME
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_validate.encryptSn
     *
     * @return the value of pano_validate.encryptSn
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_validate.encryptSn
     *
     * @param encryptSn the value for pano_validate.encryptSn
     *
     * @ibatorgenerated Tue Aug 22 18:33:21 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}