package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_bm_user", Class = PanoBmUser.class)
public class PanoBmUser<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.NICK_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String nickName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.HEAD_IMG_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long headImgSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.CITY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.IS_ALLOCATE_SPACE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Integer isAllocateSpace;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.MOBILE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.EMAIL
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.WX_ID
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String wxId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_user.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.SN
     *
     * @return the value of pano_bm_user.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.SN
     *
     * @param sn the value for pano_bm_user.SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.NICK_NAME
     *
     * @return the value of pano_bm_user.NICK_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.NICK_NAME
     *
     * @param nickName the value for pano_bm_user.NICK_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.HEAD_IMG_SN
     *
     * @return the value of pano_bm_user.HEAD_IMG_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getHeadImgSn() {
        return headImgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.HEAD_IMG_SN
     *
     * @param headImgSn the value for pano_bm_user.HEAD_IMG_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setHeadImgSn(Long headImgSn) {
        this.headImgSn = headImgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.CITY
     *
     * @return the value of pano_bm_user.CITY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.CITY
     *
     * @param city the value for pano_bm_user.CITY
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.IS_ALLOCATE_SPACE
     *
     * @return the value of pano_bm_user.IS_ALLOCATE_SPACE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Integer getIsAllocateSpace() {
        return isAllocateSpace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.IS_ALLOCATE_SPACE
     *
     * @param isAllocateSpace the value for pano_bm_user.IS_ALLOCATE_SPACE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setIsAllocateSpace(Integer isAllocateSpace) {
        this.isAllocateSpace = isAllocateSpace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.MOBILE
     *
     * @return the value of pano_bm_user.MOBILE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.MOBILE
     *
     * @param mobile the value for pano_bm_user.MOBILE
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.EMAIL
     *
     * @return the value of pano_bm_user.EMAIL
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.EMAIL
     *
     * @param email the value for pano_bm_user.EMAIL
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.WX_ID
     *
     * @return the value of pano_bm_user.WX_ID
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.WX_ID
     *
     * @param wxId the value for pano_bm_user.WX_ID
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.ADDER_SN
     *
     * @return the value of pano_bm_user.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.ADDER_SN
     *
     * @param adderSn the value for pano_bm_user.ADDER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.ADDER_NAME
     *
     * @return the value of pano_bm_user.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.ADDER_NAME
     *
     * @param adderName the value for pano_bm_user.ADDER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.ADD_TIME
     *
     * @return the value of pano_bm_user.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.ADD_TIME
     *
     * @param addTime the value for pano_bm_user.ADD_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.UPDATER_SN
     *
     * @return the value of pano_bm_user.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.UPDATER_SN
     *
     * @param updaterSn the value for pano_bm_user.UPDATER_SN
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.UPDATER_NAME
     *
     * @return the value of pano_bm_user.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.UPDATER_NAME
     *
     * @param updaterName the value for pano_bm_user.UPDATER_NAME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.UPDATE_TIME
     *
     * @return the value of pano_bm_user.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.UPDATE_TIME
     *
     * @param updateTime the value for pano_bm_user.UPDATE_TIME
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_user.encryptSn
     *
     * @return the value of pano_bm_user.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_user.encryptSn
     *
     * @param encryptSn the value for pano_bm_user.encryptSn
     *
     * @ibatorgenerated Tue Jul 11 11:54:37 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}