package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_project_package", Class = PanoProjectPackage.class)
public class PanoProjectPackage<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.ID
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.IMG_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private Long imgSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.SN
     *
     * @return the value of pano_project_package.SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.SN
     *
     * @param sn the value for pano_project_package.SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.ID
     *
     * @return the value of pano_project_package.ID
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.ID
     *
     * @param id the value for pano_project_package.ID
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.NAME
     *
     * @return the value of pano_project_package.NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.NAME
     *
     * @param name the value for pano_project_package.NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.IMG_SN
     *
     * @return the value of pano_project_package.IMG_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Long getImgSn() {
        return imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.IMG_SN
     *
     * @param imgSn the value for pano_project_package.IMG_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setImgSn(Long imgSn) {
        this.imgSn = imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.ADDER_SN
     *
     * @return the value of pano_project_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.ADDER_SN
     *
     * @param adderSn the value for pano_project_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.ADDER_NAME
     *
     * @return the value of pano_project_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.ADDER_NAME
     *
     * @param adderName the value for pano_project_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.ADD_TIME
     *
     * @return the value of pano_project_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.ADD_TIME
     *
     * @param addTime the value for pano_project_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.UPDATER_SN
     *
     * @return the value of pano_project_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.UPDATER_SN
     *
     * @param updaterSn the value for pano_project_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.UPDATER_NAME
     *
     * @return the value of pano_project_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.UPDATER_NAME
     *
     * @param updaterName the value for pano_project_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.UPDATE_TIME
     *
     * @return the value of pano_project_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.UPDATE_TIME
     *
     * @param updateTime the value for pano_project_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package.encryptSn
     *
     * @return the value of pano_project_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package.encryptSn
     *
     * @param encryptSn the value for pano_project_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:20:42 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}