package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_order", Class = PanoOrder.class)
public class PanoOrder<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ORDER_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String orderNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ORDER_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Date orderTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ADDRESS_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Long addressSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.USER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Long userSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.SUM_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private BigDecimal sumMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private BigDecimal discountMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.PAY_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private BigDecimal payMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.LEFT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private BigDecimal leftMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.PAY_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Date payTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.LEFT_PAY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Integer leftPay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.PREPAY_ID
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String prepayId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.EXTEND
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String extend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.REMARK
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.AGREE_CLAUSE
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Integer agreeClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.PARENT_ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Long parentOrderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.SN
     *
     * @return the value of pano_order.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.SN
     *
     * @param sn the value for pano_order.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ORDER_NUM
     *
     * @return the value of pano_order.ORDER_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ORDER_NUM
     *
     * @param orderNum the value for pano_order.ORDER_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ORDER_TIME
     *
     * @return the value of pano_order.ORDER_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ORDER_TIME
     *
     * @param orderTime the value for pano_order.ORDER_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.STATUS
     *
     * @return the value of pano_order.STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.STATUS
     *
     * @param status the value for pano_order.STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ADDRESS_SN
     *
     * @return the value of pano_order.ADDRESS_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getAddressSn() {
        return addressSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ADDRESS_SN
     *
     * @param addressSn the value for pano_order.ADDRESS_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setAddressSn(Long addressSn) {
        this.addressSn = addressSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.USER_SN
     *
     * @return the value of pano_order.USER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.USER_SN
     *
     * @param userSn the value for pano_order.USER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setUserSn(Long userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.SUM_MONEY
     *
     * @return the value of pano_order.SUM_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public BigDecimal getSumMoney() {
        return sumMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.SUM_MONEY
     *
     * @param sumMoney the value for pano_order.SUM_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setSumMoney(BigDecimal sumMoney) {
        this.sumMoney = sumMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.DISCOUNT_MONEY
     *
     * @return the value of pano_order.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public BigDecimal getDiscountMoney() {
        return discountMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.DISCOUNT_MONEY
     *
     * @param discountMoney the value for pano_order.DISCOUNT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setDiscountMoney(BigDecimal discountMoney) {
        this.discountMoney = discountMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.PAY_MONEY
     *
     * @return the value of pano_order.PAY_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public BigDecimal getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.PAY_MONEY
     *
     * @param payMoney the value for pano_order.PAY_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.LEFT_MONEY
     *
     * @return the value of pano_order.LEFT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public BigDecimal getLeftMoney() {
        return leftMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.LEFT_MONEY
     *
     * @param leftMoney the value for pano_order.LEFT_MONEY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setLeftMoney(BigDecimal leftMoney) {
        this.leftMoney = leftMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.PAY_TIME
     *
     * @return the value of pano_order.PAY_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.PAY_TIME
     *
     * @param payTime the value for pano_order.PAY_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.LEFT_PAY
     *
     * @return the value of pano_order.LEFT_PAY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Integer getLeftPay() {
        return leftPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.LEFT_PAY
     *
     * @param leftPay the value for pano_order.LEFT_PAY
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setLeftPay(Integer leftPay) {
        this.leftPay = leftPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.PREPAY_ID
     *
     * @return the value of pano_order.PREPAY_ID
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.PREPAY_ID
     *
     * @param prepayId the value for pano_order.PREPAY_ID
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.EXTEND
     *
     * @return the value of pano_order.EXTEND
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.EXTEND
     *
     * @param extend the value for pano_order.EXTEND
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setExtend(String extend) {
        this.extend = extend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.REMARK
     *
     * @return the value of pano_order.REMARK
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.REMARK
     *
     * @param remark the value for pano_order.REMARK
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.AGREE_CLAUSE
     *
     * @return the value of pano_order.AGREE_CLAUSE
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Integer getAgreeClause() {
        return agreeClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.AGREE_CLAUSE
     *
     * @param agreeClause the value for pano_order.AGREE_CLAUSE
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setAgreeClause(Integer agreeClause) {
        this.agreeClause = agreeClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.PARENT_ORDER_SN
     *
     * @return the value of pano_order.PARENT_ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getParentOrderSn() {
        return parentOrderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.PARENT_ORDER_SN
     *
     * @param parentOrderSn the value for pano_order.PARENT_ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setParentOrderSn(Long parentOrderSn) {
        this.parentOrderSn = parentOrderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ADDER_SN
     *
     * @return the value of pano_order.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ADDER_SN
     *
     * @param adderSn the value for pano_order.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ADDER_NAME
     *
     * @return the value of pano_order.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ADDER_NAME
     *
     * @param adderName the value for pano_order.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.ADD_TIME
     *
     * @return the value of pano_order.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.ADD_TIME
     *
     * @param addTime the value for pano_order.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.UPDATER_SN
     *
     * @return the value of pano_order.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.UPDATER_SN
     *
     * @param updaterSn the value for pano_order.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.UPDATER_NAME
     *
     * @return the value of pano_order.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.UPDATER_NAME
     *
     * @param updaterName the value for pano_order.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.UPDATE_TIME
     *
     * @return the value of pano_order.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.UPDATE_TIME
     *
     * @param updateTime the value for pano_order.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order.encryptSn
     *
     * @return the value of pano_order.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order.encryptSn
     *
     * @param encryptSn the value for pano_order.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}