package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_project_package_product", Class = PanoProjectPackageProduct.class)
public class PanoProjectPackageProduct<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.PACKAGE_TYPE_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Long packageTypeSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.PRODUCT_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Long productSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.ORDER_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Integer orderNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.ADDER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.ADD_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.PRODUCT_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private Integer productNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_package_product.encryptSn
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.SN
     *
     * @return the value of pano_project_package_product.SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.SN
     *
     * @param sn the value for pano_project_package_product.SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.PACKAGE_TYPE_SN
     *
     * @return the value of pano_project_package_product.PACKAGE_TYPE_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Long getPackageTypeSn() {
        return packageTypeSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.PACKAGE_TYPE_SN
     *
     * @param packageTypeSn the value for pano_project_package_product.PACKAGE_TYPE_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setPackageTypeSn(Long packageTypeSn) {
        this.packageTypeSn = packageTypeSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.PRODUCT_SN
     *
     * @return the value of pano_project_package_product.PRODUCT_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Long getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.PRODUCT_SN
     *
     * @param productSn the value for pano_project_package_product.PRODUCT_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setProductSn(Long productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.ORDER_NUM
     *
     * @return the value of pano_project_package_product.ORDER_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.ORDER_NUM
     *
     * @param orderNum the value for pano_project_package_product.ORDER_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.ADDER_SN
     *
     * @return the value of pano_project_package_product.ADDER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.ADDER_SN
     *
     * @param adderSn the value for pano_project_package_product.ADDER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.ADDER_NAME
     *
     * @return the value of pano_project_package_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.ADDER_NAME
     *
     * @param adderName the value for pano_project_package_product.ADDER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.ADD_TIME
     *
     * @return the value of pano_project_package_product.ADD_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.ADD_TIME
     *
     * @param addTime the value for pano_project_package_product.ADD_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.UPDATER_SN
     *
     * @return the value of pano_project_package_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.UPDATER_SN
     *
     * @param updaterSn the value for pano_project_package_product.UPDATER_SN
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.UPDATER_NAME
     *
     * @return the value of pano_project_package_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.UPDATER_NAME
     *
     * @param updaterName the value for pano_project_package_product.UPDATER_NAME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.UPDATE_TIME
     *
     * @return the value of pano_project_package_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.UPDATE_TIME
     *
     * @param updateTime the value for pano_project_package_product.UPDATE_TIME
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.PRODUCT_NUM
     *
     * @return the value of pano_project_package_product.PRODUCT_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.PRODUCT_NUM
     *
     * @param productNum the value for pano_project_package_product.PRODUCT_NUM
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_package_product.encryptSn
     *
     * @return the value of pano_project_package_product.encryptSn
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_package_product.encryptSn
     *
     * @param encryptSn the value for pano_project_package_product.encryptSn
     *
     * @ibatorgenerated Mon Sep 11 15:45:34 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}