package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_order_coupon_item", Class = PanoOrderCouponItem.class)
public class PanoOrderCouponItem<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.COUPON_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Long couponSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.CODE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private String codeNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.CODE_STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Integer codeStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.user_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Long userSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.order_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Long orderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon_item.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.SN
     *
     * @return the value of pano_order_coupon_item.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.SN
     *
     * @param sn the value for pano_order_coupon_item.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.COUPON_SN
     *
     * @return the value of pano_order_coupon_item.COUPON_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getCouponSn() {
        return couponSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.COUPON_SN
     *
     * @param couponSn the value for pano_order_coupon_item.COUPON_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setCouponSn(Long couponSn) {
        this.couponSn = couponSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.CODE_NUM
     *
     * @return the value of pano_order_coupon_item.CODE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public String getCodeNum() {
        return codeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.CODE_NUM
     *
     * @param codeNum the value for pano_order_coupon_item.CODE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setCodeNum(String codeNum) {
        this.codeNum = codeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.CODE_STATUS
     *
     * @return the value of pano_order_coupon_item.CODE_STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Integer getCodeStatus() {
        return codeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.CODE_STATUS
     *
     * @param codeStatus the value for pano_order_coupon_item.CODE_STATUS
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setCodeStatus(Integer codeStatus) {
        this.codeStatus = codeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.user_sn
     *
     * @return the value of pano_order_coupon_item.user_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.user_sn
     *
     * @param userSn the value for pano_order_coupon_item.user_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setUserSn(Long userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.order_sn
     *
     * @return the value of pano_order_coupon_item.order_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.order_sn
     *
     * @param orderSn the value for pano_order_coupon_item.order_sn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.ADDER_SN
     *
     * @return the value of pano_order_coupon_item.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.ADDER_SN
     *
     * @param adderSn the value for pano_order_coupon_item.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.ADDER_NAME
     *
     * @return the value of pano_order_coupon_item.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.ADDER_NAME
     *
     * @param adderName the value for pano_order_coupon_item.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.ADD_TIME
     *
     * @return the value of pano_order_coupon_item.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.ADD_TIME
     *
     * @param addTime the value for pano_order_coupon_item.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.UPDATER_SN
     *
     * @return the value of pano_order_coupon_item.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.UPDATER_SN
     *
     * @param updaterSn the value for pano_order_coupon_item.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.UPDATER_NAME
     *
     * @return the value of pano_order_coupon_item.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.UPDATER_NAME
     *
     * @param updaterName the value for pano_order_coupon_item.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.UPDATE_TIME
     *
     * @return the value of pano_order_coupon_item.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.UPDATE_TIME
     *
     * @param updateTime the value for pano_order_coupon_item.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon_item.encryptSn
     *
     * @return the value of pano_order_coupon_item.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon_item.encryptSn
     *
     * @param encryptSn the value for pano_order_coupon_item.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}