package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_order_package", Class = PanoOrderPackage.class)
public class PanoOrderPackage<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Long orderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.HOUSE_PACKAGE_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Long housePackageSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.PURCHASE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Integer purchaseNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.PRICE
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private BigDecimal price;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.SN
     *
     * @return the value of pano_order_package.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.SN
     *
     * @param sn the value for pano_order_package.SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.ORDER_SN
     *
     * @return the value of pano_order_package.ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.ORDER_SN
     *
     * @param orderSn the value for pano_order_package.ORDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.HOUSE_PACKAGE_SN
     *
     * @return the value of pano_order_package.HOUSE_PACKAGE_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Long getHousePackageSn() {
        return housePackageSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.HOUSE_PACKAGE_SN
     *
     * @param housePackageSn the value for pano_order_package.HOUSE_PACKAGE_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setHousePackageSn(Long housePackageSn) {
        this.housePackageSn = housePackageSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.PURCHASE_NUM
     *
     * @return the value of pano_order_package.PURCHASE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Integer getPurchaseNum() {
        return purchaseNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.PURCHASE_NUM
     *
     * @param purchaseNum the value for pano_order_package.PURCHASE_NUM
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setPurchaseNum(Integer purchaseNum) {
        this.purchaseNum = purchaseNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.PRICE
     *
     * @return the value of pano_order_package.PRICE
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.PRICE
     *
     * @param price the value for pano_order_package.PRICE
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.ADDER_SN
     *
     * @return the value of pano_order_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.ADDER_SN
     *
     * @param adderSn the value for pano_order_package.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.ADDER_NAME
     *
     * @return the value of pano_order_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.ADDER_NAME
     *
     * @param adderName the value for pano_order_package.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.ADD_TIME
     *
     * @return the value of pano_order_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.ADD_TIME
     *
     * @param addTime the value for pano_order_package.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.UPDATER_SN
     *
     * @return the value of pano_order_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.UPDATER_SN
     *
     * @param updaterSn the value for pano_order_package.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.UPDATER_NAME
     *
     * @return the value of pano_order_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.UPDATER_NAME
     *
     * @param updaterName the value for pano_order_package.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.UPDATE_TIME
     *
     * @return the value of pano_order_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.UPDATE_TIME
     *
     * @param updateTime the value for pano_order_package.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_package.encryptSn
     *
     * @return the value of pano_order_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_package.encryptSn
     *
     * @param encryptSn the value for pano_order_package.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 14:59:46 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}