package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "pano_perspective_element_product", Class = PanoPerspectiveElementProduct.class)
public class PanoPerspectiveElementProductCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public PanoPerspectiveElementProductCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public PanoPerspectiveElementProductCriteria(PanoPerspectiveElementProductCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public PanoPerspectiveElementProductCriteria(Object record, PanoPerspectiveElementProductCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pano_perspective_element_product
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andElementSnIsNull() {
            addCriterion("ELEMENT_SN is null");
            return this;
        }

        public Criteria andElementSnIsNotNull() {
            addCriterion("ELEMENT_SN is not null");
            return this;
        }

        public Criteria andElementSnEqualTo(Long value) {
            addCriterion("ELEMENT_SN =", value, "elementSn");
            return this;
        }

        public Criteria andElementSnNotEqualTo(Long value) {
            addCriterion("ELEMENT_SN <>", value, "elementSn");
            return this;
        }

        public Criteria andElementSnGreaterThan(Long value) {
            addCriterion("ELEMENT_SN >", value, "elementSn");
            return this;
        }

        public Criteria andElementSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ELEMENT_SN >=", value, "elementSn");
            return this;
        }

        public Criteria andElementSnLessThan(Long value) {
            addCriterion("ELEMENT_SN <", value, "elementSn");
            return this;
        }

        public Criteria andElementSnLessThanOrEqualTo(Long value) {
            addCriterion("ELEMENT_SN <=", value, "elementSn");
            return this;
        }

        public Criteria andElementSnIn(List values) {
            addCriterion("ELEMENT_SN in", values, "elementSn");
            return this;
        }

        public Criteria andElementSnNotIn(List values) {
            addCriterion("ELEMENT_SN not in", values, "elementSn");
            return this;
        }

        public Criteria andElementSnBetween(Long value1, Long value2) {
            addCriterion("ELEMENT_SN between", value1, value2, "elementSn");
            return this;
        }

        public Criteria andElementSnNotBetween(Long value1, Long value2) {
            addCriterion("ELEMENT_SN not between", value1, value2, "elementSn");
            return this;
        }

        public Criteria andProductSnIsNull() {
            addCriterion("PRODUCT_SN is null");
            return this;
        }

        public Criteria andProductSnIsNotNull() {
            addCriterion("PRODUCT_SN is not null");
            return this;
        }

        public Criteria andProductSnEqualTo(Long value) {
            addCriterion("PRODUCT_SN =", value, "productSn");
            return this;
        }

        public Criteria andProductSnNotEqualTo(Long value) {
            addCriterion("PRODUCT_SN <>", value, "productSn");
            return this;
        }

        public Criteria andProductSnGreaterThan(Long value) {
            addCriterion("PRODUCT_SN >", value, "productSn");
            return this;
        }

        public Criteria andProductSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_SN >=", value, "productSn");
            return this;
        }

        public Criteria andProductSnLessThan(Long value) {
            addCriterion("PRODUCT_SN <", value, "productSn");
            return this;
        }

        public Criteria andProductSnLessThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_SN <=", value, "productSn");
            return this;
        }

        public Criteria andProductSnIn(List values) {
            addCriterion("PRODUCT_SN in", values, "productSn");
            return this;
        }

        public Criteria andProductSnNotIn(List values) {
            addCriterion("PRODUCT_SN not in", values, "productSn");
            return this;
        }

        public Criteria andProductSnBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_SN between", value1, value2, "productSn");
            return this;
        }

        public Criteria andProductSnNotBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_SN not between", value1, value2, "productSn");
            return this;
        }

        public Criteria andProductMapIsNull() {
            addCriterion("PRODUCT_MAP is null");
            return this;
        }

        public Criteria andProductMapIsNotNull() {
            addCriterion("PRODUCT_MAP is not null");
            return this;
        }

        public Criteria andProductMapEqualTo(Long value) {
            addCriterion("PRODUCT_MAP =", value, "productMap");
            return this;
        }

        public Criteria andProductMapNotEqualTo(Long value) {
            addCriterion("PRODUCT_MAP <>", value, "productMap");
            return this;
        }

        public Criteria andProductMapGreaterThan(Long value) {
            addCriterion("PRODUCT_MAP >", value, "productMap");
            return this;
        }

        public Criteria andProductMapGreaterThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_MAP >=", value, "productMap");
            return this;
        }

        public Criteria andProductMapLessThan(Long value) {
            addCriterion("PRODUCT_MAP <", value, "productMap");
            return this;
        }

        public Criteria andProductMapLessThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_MAP <=", value, "productMap");
            return this;
        }

        public Criteria andProductMapIn(List values) {
            addCriterion("PRODUCT_MAP in", values, "productMap");
            return this;
        }

        public Criteria andProductMapNotIn(List values) {
            addCriterion("PRODUCT_MAP not in", values, "productMap");
            return this;
        }

        public Criteria andProductMapBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_MAP between", value1, value2, "productMap");
            return this;
        }

        public Criteria andProductMapNotBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_MAP not between", value1, value2, "productMap");
            return this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return this;
        }

        public Criteria andPositionIn(List values) {
            addCriterion("position in", values, "position");
            return this;
        }

        public Criteria andPositionNotIn(List values) {
            addCriterion("position not in", values, "position");
            return this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return this;
        }

        public Criteria andScaleIsNull() {
            addCriterion("scale is null");
            return this;
        }

        public Criteria andScaleIsNotNull() {
            addCriterion("scale is not null");
            return this;
        }

        public Criteria andScaleEqualTo(String value) {
            addCriterion("scale =", value, "scale");
            return this;
        }

        public Criteria andScaleNotEqualTo(String value) {
            addCriterion("scale <>", value, "scale");
            return this;
        }

        public Criteria andScaleGreaterThan(String value) {
            addCriterion("scale >", value, "scale");
            return this;
        }

        public Criteria andScaleGreaterThanOrEqualTo(String value) {
            addCriterion("scale >=", value, "scale");
            return this;
        }

        public Criteria andScaleLessThan(String value) {
            addCriterion("scale <", value, "scale");
            return this;
        }

        public Criteria andScaleLessThanOrEqualTo(String value) {
            addCriterion("scale <=", value, "scale");
            return this;
        }

        public Criteria andScaleLike(String value) {
            addCriterion("scale like", value, "scale");
            return this;
        }

        public Criteria andScaleNotLike(String value) {
            addCriterion("scale not like", value, "scale");
            return this;
        }

        public Criteria andScaleIn(List values) {
            addCriterion("scale in", values, "scale");
            return this;
        }

        public Criteria andScaleNotIn(List values) {
            addCriterion("scale not in", values, "scale");
            return this;
        }

        public Criteria andScaleBetween(String value1, String value2) {
            addCriterion("scale between", value1, value2, "scale");
            return this;
        }

        public Criteria andScaleNotBetween(String value1, String value2) {
            addCriterion("scale not between", value1, value2, "scale");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andRepeatingIsNull() {
            addCriterion("repeating is null");
            return this;
        }

        public Criteria andRepeatingIsNotNull() {
            addCriterion("repeating is not null");
            return this;
        }

        public Criteria andRepeatingEqualTo(String value) {
            addCriterion("repeating =", value, "repeating");
            return this;
        }

        public Criteria andRepeatingNotEqualTo(String value) {
            addCriterion("repeating <>", value, "repeating");
            return this;
        }

        public Criteria andRepeatingGreaterThan(String value) {
            addCriterion("repeating >", value, "repeating");
            return this;
        }

        public Criteria andRepeatingGreaterThanOrEqualTo(String value) {
            addCriterion("repeating >=", value, "repeating");
            return this;
        }

        public Criteria andRepeatingLessThan(String value) {
            addCriterion("repeating <", value, "repeating");
            return this;
        }

        public Criteria andRepeatingLessThanOrEqualTo(String value) {
            addCriterion("repeating <=", value, "repeating");
            return this;
        }

        public Criteria andRepeatingLike(String value) {
            addCriterion("repeating like", value, "repeating");
            return this;
        }

        public Criteria andRepeatingNotLike(String value) {
            addCriterion("repeating not like", value, "repeating");
            return this;
        }

        public Criteria andRepeatingIn(List values) {
            addCriterion("repeating in", values, "repeating");
            return this;
        }

        public Criteria andRepeatingNotIn(List values) {
            addCriterion("repeating not in", values, "repeating");
            return this;
        }

        public Criteria andRepeatingBetween(String value1, String value2) {
            addCriterion("repeating between", value1, value2, "repeating");
            return this;
        }

        public Criteria andRepeatingNotBetween(String value1, String value2) {
            addCriterion("repeating not between", value1, value2, "repeating");
            return this;
        }
    }
}