package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_perspective_element_product", Class = PanoPerspectiveElementProduct.class)
public class PanoPerspectiveElementProduct<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.ELEMENT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long elementSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.PRODUCT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long productSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.PRODUCT_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long productMap;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.position
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String position;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.scale
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String scale;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.repeating
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String repeating;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_element_product.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.SN
     *
     * @return the value of pano_perspective_element_product.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.SN
     *
     * @param sn the value for pano_perspective_element_product.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.ELEMENT_SN
     *
     * @return the value of pano_perspective_element_product.ELEMENT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getElementSn() {
        return elementSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.ELEMENT_SN
     *
     * @param elementSn the value for pano_perspective_element_product.ELEMENT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setElementSn(Long elementSn) {
        this.elementSn = elementSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.PRODUCT_SN
     *
     * @return the value of pano_perspective_element_product.PRODUCT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.PRODUCT_SN
     *
     * @param productSn the value for pano_perspective_element_product.PRODUCT_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setProductSn(Long productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.PRODUCT_MAP
     *
     * @return the value of pano_perspective_element_product.PRODUCT_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getProductMap() {
        return productMap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.PRODUCT_MAP
     *
     * @param productMap the value for pano_perspective_element_product.PRODUCT_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setProductMap(Long productMap) {
        this.productMap = productMap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.position
     *
     * @return the value of pano_perspective_element_product.position
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.position
     *
     * @param position the value for pano_perspective_element_product.position
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.scale
     *
     * @return the value of pano_perspective_element_product.scale
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.scale
     *
     * @param scale the value for pano_perspective_element_product.scale
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setScale(String scale) {
        this.scale = scale;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.ADDER_SN
     *
     * @return the value of pano_perspective_element_product.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.ADDER_SN
     *
     * @param adderSn the value for pano_perspective_element_product.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.ADDER_NAME
     *
     * @return the value of pano_perspective_element_product.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.ADDER_NAME
     *
     * @param adderName the value for pano_perspective_element_product.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.ADD_TIME
     *
     * @return the value of pano_perspective_element_product.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.ADD_TIME
     *
     * @param addTime the value for pano_perspective_element_product.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.UPDATER_SN
     *
     * @return the value of pano_perspective_element_product.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.UPDATER_SN
     *
     * @param updaterSn the value for pano_perspective_element_product.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.UPDATER_NAME
     *
     * @return the value of pano_perspective_element_product.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.UPDATER_NAME
     *
     * @param updaterName the value for pano_perspective_element_product.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.UPDATE_TIME
     *
     * @return the value of pano_perspective_element_product.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.UPDATE_TIME
     *
     * @param updateTime the value for pano_perspective_element_product.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.repeating
     *
     * @return the value of pano_perspective_element_product.repeating
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getRepeating() {
        return repeating;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.repeating
     *
     * @param repeating the value for pano_perspective_element_product.repeating
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setRepeating(String repeating) {
        this.repeating = repeating;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_element_product.encryptSn
     *
     * @return the value of pano_perspective_element_product.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_element_product.encryptSn
     *
     * @param encryptSn the value for pano_perspective_element_product.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}