package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_user_receive_address", Class = PanoUserReceiveAddress.class)
public class PanoUserReceiveAddress<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.USER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.SEX
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Integer sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.BACKUP_MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String backupMobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.PROVINCE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.CITY
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.AREA
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String area;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.STREET
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String street;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.DEFAULT_FIRST
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Integer defaultFirst;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.USER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Long userSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.ADDER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.ADD_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_user_receive_address.encryptSn
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.SN
     *
     * @return the value of pano_user_receive_address.SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.SN
     *
     * @param sn the value for pano_user_receive_address.SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.USER_NAME
     *
     * @return the value of pano_user_receive_address.USER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.USER_NAME
     *
     * @param userName the value for pano_user_receive_address.USER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.SEX
     *
     * @return the value of pano_user_receive_address.SEX
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.SEX
     *
     * @param sex the value for pano_user_receive_address.SEX
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.MOBILE
     *
     * @return the value of pano_user_receive_address.MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.MOBILE
     *
     * @param mobile the value for pano_user_receive_address.MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.BACKUP_MOBILE
     *
     * @return the value of pano_user_receive_address.BACKUP_MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getBackupMobile() {
        return backupMobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.BACKUP_MOBILE
     *
     * @param backupMobile the value for pano_user_receive_address.BACKUP_MOBILE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setBackupMobile(String backupMobile) {
        this.backupMobile = backupMobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.PROVINCE
     *
     * @return the value of pano_user_receive_address.PROVINCE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.PROVINCE
     *
     * @param province the value for pano_user_receive_address.PROVINCE
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.CITY
     *
     * @return the value of pano_user_receive_address.CITY
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.CITY
     *
     * @param city the value for pano_user_receive_address.CITY
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.AREA
     *
     * @return the value of pano_user_receive_address.AREA
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.AREA
     *
     * @param area the value for pano_user_receive_address.AREA
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.STREET
     *
     * @return the value of pano_user_receive_address.STREET
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.STREET
     *
     * @param street the value for pano_user_receive_address.STREET
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.DEFAULT_FIRST
     *
     * @return the value of pano_user_receive_address.DEFAULT_FIRST
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Integer getDefaultFirst() {
        return defaultFirst;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.DEFAULT_FIRST
     *
     * @param defaultFirst the value for pano_user_receive_address.DEFAULT_FIRST
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setDefaultFirst(Integer defaultFirst) {
        this.defaultFirst = defaultFirst;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.USER_SN
     *
     * @return the value of pano_user_receive_address.USER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Long getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.USER_SN
     *
     * @param userSn the value for pano_user_receive_address.USER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setUserSn(Long userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.ADDER_SN
     *
     * @return the value of pano_user_receive_address.ADDER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.ADDER_SN
     *
     * @param adderSn the value for pano_user_receive_address.ADDER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.ADDER_NAME
     *
     * @return the value of pano_user_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.ADDER_NAME
     *
     * @param adderName the value for pano_user_receive_address.ADDER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.ADD_TIME
     *
     * @return the value of pano_user_receive_address.ADD_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.ADD_TIME
     *
     * @param addTime the value for pano_user_receive_address.ADD_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.UPDATER_SN
     *
     * @return the value of pano_user_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.UPDATER_SN
     *
     * @param updaterSn the value for pano_user_receive_address.UPDATER_SN
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.UPDATER_NAME
     *
     * @return the value of pano_user_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.UPDATER_NAME
     *
     * @param updaterName the value for pano_user_receive_address.UPDATER_NAME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.UPDATE_TIME
     *
     * @return the value of pano_user_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.UPDATE_TIME
     *
     * @param updateTime the value for pano_user_receive_address.UPDATE_TIME
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_user_receive_address.encryptSn
     *
     * @return the value of pano_user_receive_address.encryptSn
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_user_receive_address.encryptSn
     *
     * @param encryptSn the value for pano_user_receive_address.encryptSn
     *
     * @ibatorgenerated Wed Aug 23 13:56:53 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}