package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_project_house_style", Class = PanoProjectHouseStyle.class)
public class PanoProjectHouseStyle<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.HOUSE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long houseSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.STYLE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long styleSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.PANO_ID
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long panoId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long projectSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.img_sn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private Long imgSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_style.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.SN
     *
     * @return the value of pano_project_house_style.SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.SN
     *
     * @param sn the value for pano_project_house_style.SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.HOUSE_SN
     *
     * @return the value of pano_project_house_style.HOUSE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getHouseSn() {
        return houseSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.HOUSE_SN
     *
     * @param houseSn the value for pano_project_house_style.HOUSE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setHouseSn(Long houseSn) {
        this.houseSn = houseSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.STYLE_SN
     *
     * @return the value of pano_project_house_style.STYLE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getStyleSn() {
        return styleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.STYLE_SN
     *
     * @param styleSn the value for pano_project_house_style.STYLE_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setStyleSn(Long styleSn) {
        this.styleSn = styleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.PANO_ID
     *
     * @return the value of pano_project_house_style.PANO_ID
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getPanoId() {
        return panoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.PANO_ID
     *
     * @param panoId the value for pano_project_house_style.PANO_ID
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setPanoId(Long panoId) {
        this.panoId = panoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.PROJECT_SN
     *
     * @return the value of pano_project_house_style.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getProjectSn() {
        return projectSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.PROJECT_SN
     *
     * @param projectSn the value for pano_project_house_style.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setProjectSn(Long projectSn) {
        this.projectSn = projectSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.ADDER_SN
     *
     * @return the value of pano_project_house_style.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.ADDER_SN
     *
     * @param adderSn the value for pano_project_house_style.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.ADDER_NAME
     *
     * @return the value of pano_project_house_style.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.ADDER_NAME
     *
     * @param adderName the value for pano_project_house_style.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.ADD_TIME
     *
     * @return the value of pano_project_house_style.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.ADD_TIME
     *
     * @param addTime the value for pano_project_house_style.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.UPDATER_SN
     *
     * @return the value of pano_project_house_style.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.UPDATER_SN
     *
     * @param updaterSn the value for pano_project_house_style.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.UPDATER_NAME
     *
     * @return the value of pano_project_house_style.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.UPDATER_NAME
     *
     * @param updaterName the value for pano_project_house_style.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.UPDATE_TIME
     *
     * @return the value of pano_project_house_style.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.UPDATE_TIME
     *
     * @param updateTime the value for pano_project_house_style.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.img_sn
     *
     * @return the value of pano_project_house_style.img_sn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public Long getImgSn() {
        return imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.img_sn
     *
     * @param imgSn the value for pano_project_house_style.img_sn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setImgSn(Long imgSn) {
        this.imgSn = imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_style.encryptSn
     *
     * @return the value of pano_project_house_style.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_style.encryptSn
     *
     * @param encryptSn the value for pano_project_house_style.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 12:52:48 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}