package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_project_house_package", Class = PanoProjectHousePackage.class)
public class PanoProjectHousePackage<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.PACKAGE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Long packageSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Long houseStyleSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.PACKAGE_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private BigDecimal packagePrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.DISCOUNT_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private BigDecimal discountPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.IMG_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Long imgSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_project_house_package.encryptSn
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.SN
     *
     * @return the value of pano_project_house_package.SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.SN
     *
     * @param sn the value for pano_project_house_package.SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.PACKAGE_SN
     *
     * @return the value of pano_project_house_package.PACKAGE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getPackageSn() {
        return packageSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.PACKAGE_SN
     *
     * @param packageSn the value for pano_project_house_package.PACKAGE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setPackageSn(Long packageSn) {
        this.packageSn = packageSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.HOUSE_STYLE_SN
     *
     * @return the value of pano_project_house_package.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getHouseStyleSn() {
        return houseStyleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.HOUSE_STYLE_SN
     *
     * @param houseStyleSn the value for pano_project_house_package.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setHouseStyleSn(Long houseStyleSn) {
        this.houseStyleSn = houseStyleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.PACKAGE_PRICE
     *
     * @return the value of pano_project_house_package.PACKAGE_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public BigDecimal getPackagePrice() {
        return packagePrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.PACKAGE_PRICE
     *
     * @param packagePrice the value for pano_project_house_package.PACKAGE_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setPackagePrice(BigDecimal packagePrice) {
        this.packagePrice = packagePrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.DISCOUNT_PRICE
     *
     * @return the value of pano_project_house_package.DISCOUNT_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.DISCOUNT_PRICE
     *
     * @param discountPrice the value for pano_project_house_package.DISCOUNT_PRICE
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.IMG_SN
     *
     * @return the value of pano_project_house_package.IMG_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getImgSn() {
        return imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.IMG_SN
     *
     * @param imgSn the value for pano_project_house_package.IMG_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setImgSn(Long imgSn) {
        this.imgSn = imgSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.ADDER_SN
     *
     * @return the value of pano_project_house_package.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.ADDER_SN
     *
     * @param adderSn the value for pano_project_house_package.ADDER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.ADDER_NAME
     *
     * @return the value of pano_project_house_package.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.ADDER_NAME
     *
     * @param adderName the value for pano_project_house_package.ADDER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.ADD_TIME
     *
     * @return the value of pano_project_house_package.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.ADD_TIME
     *
     * @param addTime the value for pano_project_house_package.ADD_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.UPDATER_SN
     *
     * @return the value of pano_project_house_package.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.UPDATER_SN
     *
     * @param updaterSn the value for pano_project_house_package.UPDATER_SN
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.UPDATER_NAME
     *
     * @return the value of pano_project_house_package.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.UPDATER_NAME
     *
     * @param updaterName the value for pano_project_house_package.UPDATER_NAME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.UPDATE_TIME
     *
     * @return the value of pano_project_house_package.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.UPDATE_TIME
     *
     * @param updateTime the value for pano_project_house_package.UPDATE_TIME
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_project_house_package.encryptSn
     *
     * @return the value of pano_project_house_package.encryptSn
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_project_house_package.encryptSn
     *
     * @param encryptSn the value for pano_project_house_package.encryptSn
     *
     * @ibatorgenerated Thu Aug 24 17:48:31 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}