package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "pano_order", Class = PanoOrder.class)
public class PanoOrderCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public PanoOrderCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public PanoOrderCriteria(PanoOrderCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public PanoOrderCriteria(Object record, PanoOrderCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pano_order
     *
     * @ibatorgenerated Fri Aug 25 14:59:05 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("ORDER_NUM is null");
            return this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("ORDER_NUM is not null");
            return this;
        }

        public Criteria andOrderNumEqualTo(String value) {
            addCriterion("ORDER_NUM =", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotEqualTo(String value) {
            addCriterion("ORDER_NUM <>", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThan(String value) {
            addCriterion("ORDER_NUM >", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM >=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThan(String value) {
            addCriterion("ORDER_NUM <", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NUM <=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLike(String value) {
            addCriterion("ORDER_NUM like", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotLike(String value) {
            addCriterion("ORDER_NUM not like", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumIn(List values) {
            addCriterion("ORDER_NUM in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotIn(List values) {
            addCriterion("ORDER_NUM not in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumBetween(String value1, String value2) {
            addCriterion("ORDER_NUM between", value1, value2, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotBetween(String value1, String value2) {
            addCriterion("ORDER_NUM not between", value1, value2, "orderNum");
            return this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("ORDER_TIME is null");
            return this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("ORDER_TIME is not null");
            return this;
        }

        public Criteria andOrderTimeEqualTo(Date value) {
            addCriterion("ORDER_TIME =", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotEqualTo(Date value) {
            addCriterion("ORDER_TIME <>", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThan(Date value) {
            addCriterion("ORDER_TIME >", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ORDER_TIME >=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThan(Date value) {
            addCriterion("ORDER_TIME <", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("ORDER_TIME <=", value, "orderTime");
            return this;
        }

        public Criteria andOrderTimeIn(List values) {
            addCriterion("ORDER_TIME in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotIn(List values) {
            addCriterion("ORDER_TIME not in", values, "orderTime");
            return this;
        }

        public Criteria andOrderTimeBetween(Date value1, Date value2) {
            addCriterion("ORDER_TIME between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("ORDER_TIME not between", value1, value2, "orderTime");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andAddressSnIsNull() {
            addCriterion("ADDRESS_SN is null");
            return this;
        }

        public Criteria andAddressSnIsNotNull() {
            addCriterion("ADDRESS_SN is not null");
            return this;
        }

        public Criteria andAddressSnEqualTo(Long value) {
            addCriterion("ADDRESS_SN =", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnNotEqualTo(Long value) {
            addCriterion("ADDRESS_SN <>", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnGreaterThan(Long value) {
            addCriterion("ADDRESS_SN >", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDRESS_SN >=", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnLessThan(Long value) {
            addCriterion("ADDRESS_SN <", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDRESS_SN <=", value, "addressSn");
            return this;
        }

        public Criteria andAddressSnIn(List values) {
            addCriterion("ADDRESS_SN in", values, "addressSn");
            return this;
        }

        public Criteria andAddressSnNotIn(List values) {
            addCriterion("ADDRESS_SN not in", values, "addressSn");
            return this;
        }

        public Criteria andAddressSnBetween(Long value1, Long value2) {
            addCriterion("ADDRESS_SN between", value1, value2, "addressSn");
            return this;
        }

        public Criteria andAddressSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDRESS_SN not between", value1, value2, "addressSn");
            return this;
        }

        public Criteria andUserSnIsNull() {
            addCriterion("USER_SN is null");
            return this;
        }

        public Criteria andUserSnIsNotNull() {
            addCriterion("USER_SN is not null");
            return this;
        }

        public Criteria andUserSnEqualTo(Long value) {
            addCriterion("USER_SN =", value, "userSn");
            return this;
        }

        public Criteria andUserSnNotEqualTo(Long value) {
            addCriterion("USER_SN <>", value, "userSn");
            return this;
        }

        public Criteria andUserSnGreaterThan(Long value) {
            addCriterion("USER_SN >", value, "userSn");
            return this;
        }

        public Criteria andUserSnGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_SN >=", value, "userSn");
            return this;
        }

        public Criteria andUserSnLessThan(Long value) {
            addCriterion("USER_SN <", value, "userSn");
            return this;
        }

        public Criteria andUserSnLessThanOrEqualTo(Long value) {
            addCriterion("USER_SN <=", value, "userSn");
            return this;
        }

        public Criteria andUserSnIn(List values) {
            addCriterion("USER_SN in", values, "userSn");
            return this;
        }

        public Criteria andUserSnNotIn(List values) {
            addCriterion("USER_SN not in", values, "userSn");
            return this;
        }

        public Criteria andUserSnBetween(Long value1, Long value2) {
            addCriterion("USER_SN between", value1, value2, "userSn");
            return this;
        }

        public Criteria andUserSnNotBetween(Long value1, Long value2) {
            addCriterion("USER_SN not between", value1, value2, "userSn");
            return this;
        }

        public Criteria andSumMoneyIsNull() {
            addCriterion("SUM_MONEY is null");
            return this;
        }

        public Criteria andSumMoneyIsNotNull() {
            addCriterion("SUM_MONEY is not null");
            return this;
        }

        public Criteria andSumMoneyEqualTo(BigDecimal value) {
            addCriterion("SUM_MONEY =", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyNotEqualTo(BigDecimal value) {
            addCriterion("SUM_MONEY <>", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyGreaterThan(BigDecimal value) {
            addCriterion("SUM_MONEY >", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MONEY >=", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyLessThan(BigDecimal value) {
            addCriterion("SUM_MONEY <", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MONEY <=", value, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyIn(List values) {
            addCriterion("SUM_MONEY in", values, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyNotIn(List values) {
            addCriterion("SUM_MONEY not in", values, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MONEY between", value1, value2, "sumMoney");
            return this;
        }

        public Criteria andSumMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MONEY not between", value1, value2, "sumMoney");
            return this;
        }

        public Criteria andDiscountMoneyIsNull() {
            addCriterion("DISCOUNT_MONEY is null");
            return this;
        }

        public Criteria andDiscountMoneyIsNotNull() {
            addCriterion("DISCOUNT_MONEY is not null");
            return this;
        }

        public Criteria andDiscountMoneyEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY =", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <>", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyGreaterThan(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY >", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY >=", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyLessThan(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_MONEY <=", value, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyIn(List values) {
            addCriterion("DISCOUNT_MONEY in", values, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotIn(List values) {
            addCriterion("DISCOUNT_MONEY not in", values, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_MONEY between", value1, value2, "discountMoney");
            return this;
        }

        public Criteria andDiscountMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_MONEY not between", value1, value2, "discountMoney");
            return this;
        }

        public Criteria andPayMoneyIsNull() {
            addCriterion("PAY_MONEY is null");
            return this;
        }

        public Criteria andPayMoneyIsNotNull() {
            addCriterion("PAY_MONEY is not null");
            return this;
        }

        public Criteria andPayMoneyEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY =", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY <>", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThan(BigDecimal value) {
            addCriterion("PAY_MONEY >", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY >=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThan(BigDecimal value) {
            addCriterion("PAY_MONEY <", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY <=", value, "payMoney");
            return this;
        }

        public Criteria andPayMoneyIn(List values) {
            addCriterion("PAY_MONEY in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotIn(List values) {
            addCriterion("PAY_MONEY not in", values, "payMoney");
            return this;
        }

        public Criteria andPayMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MONEY between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andPayMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MONEY not between", value1, value2, "payMoney");
            return this;
        }

        public Criteria andLeftMoneyIsNull() {
            addCriterion("LEFT_MONEY is null");
            return this;
        }

        public Criteria andLeftMoneyIsNotNull() {
            addCriterion("LEFT_MONEY is not null");
            return this;
        }

        public Criteria andLeftMoneyEqualTo(BigDecimal value) {
            addCriterion("LEFT_MONEY =", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyNotEqualTo(BigDecimal value) {
            addCriterion("LEFT_MONEY <>", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyGreaterThan(BigDecimal value) {
            addCriterion("LEFT_MONEY >", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEFT_MONEY >=", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyLessThan(BigDecimal value) {
            addCriterion("LEFT_MONEY <", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEFT_MONEY <=", value, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyIn(List values) {
            addCriterion("LEFT_MONEY in", values, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyNotIn(List values) {
            addCriterion("LEFT_MONEY not in", values, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEFT_MONEY between", value1, value2, "leftMoney");
            return this;
        }

        public Criteria andLeftMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEFT_MONEY not between", value1, value2, "leftMoney");
            return this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PAY_TIME is null");
            return this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PAY_TIME is not null");
            return this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("PAY_TIME =", value, "payTime");
            return this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("PAY_TIME <>", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("PAY_TIME >", value, "payTime");
            return this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PAY_TIME >=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("PAY_TIME <", value, "payTime");
            return this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("PAY_TIME <=", value, "payTime");
            return this;
        }

        public Criteria andPayTimeIn(List values) {
            addCriterion("PAY_TIME in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeNotIn(List values) {
            addCriterion("PAY_TIME not in", values, "payTime");
            return this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("PAY_TIME between", value1, value2, "payTime");
            return this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("PAY_TIME not between", value1, value2, "payTime");
            return this;
        }

        public Criteria andLeftPayIsNull() {
            addCriterion("LEFT_PAY is null");
            return this;
        }

        public Criteria andLeftPayIsNotNull() {
            addCriterion("LEFT_PAY is not null");
            return this;
        }

        public Criteria andLeftPayEqualTo(Integer value) {
            addCriterion("LEFT_PAY =", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayNotEqualTo(Integer value) {
            addCriterion("LEFT_PAY <>", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayGreaterThan(Integer value) {
            addCriterion("LEFT_PAY >", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEFT_PAY >=", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayLessThan(Integer value) {
            addCriterion("LEFT_PAY <", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayLessThanOrEqualTo(Integer value) {
            addCriterion("LEFT_PAY <=", value, "leftPay");
            return this;
        }

        public Criteria andLeftPayIn(List values) {
            addCriterion("LEFT_PAY in", values, "leftPay");
            return this;
        }

        public Criteria andLeftPayNotIn(List values) {
            addCriterion("LEFT_PAY not in", values, "leftPay");
            return this;
        }

        public Criteria andLeftPayBetween(Integer value1, Integer value2) {
            addCriterion("LEFT_PAY between", value1, value2, "leftPay");
            return this;
        }

        public Criteria andLeftPayNotBetween(Integer value1, Integer value2) {
            addCriterion("LEFT_PAY not between", value1, value2, "leftPay");
            return this;
        }

        public Criteria andPrepayIdIsNull() {
            addCriterion("PREPAY_ID is null");
            return this;
        }

        public Criteria andPrepayIdIsNotNull() {
            addCriterion("PREPAY_ID is not null");
            return this;
        }

        public Criteria andPrepayIdEqualTo(String value) {
            addCriterion("PREPAY_ID =", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotEqualTo(String value) {
            addCriterion("PREPAY_ID <>", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdGreaterThan(String value) {
            addCriterion("PREPAY_ID >", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdGreaterThanOrEqualTo(String value) {
            addCriterion("PREPAY_ID >=", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLessThan(String value) {
            addCriterion("PREPAY_ID <", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLessThanOrEqualTo(String value) {
            addCriterion("PREPAY_ID <=", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdLike(String value) {
            addCriterion("PREPAY_ID like", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotLike(String value) {
            addCriterion("PREPAY_ID not like", value, "prepayId");
            return this;
        }

        public Criteria andPrepayIdIn(List values) {
            addCriterion("PREPAY_ID in", values, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotIn(List values) {
            addCriterion("PREPAY_ID not in", values, "prepayId");
            return this;
        }

        public Criteria andPrepayIdBetween(String value1, String value2) {
            addCriterion("PREPAY_ID between", value1, value2, "prepayId");
            return this;
        }

        public Criteria andPrepayIdNotBetween(String value1, String value2) {
            addCriterion("PREPAY_ID not between", value1, value2, "prepayId");
            return this;
        }

        public Criteria andExtendIsNull() {
            addCriterion("EXTEND is null");
            return this;
        }

        public Criteria andExtendIsNotNull() {
            addCriterion("EXTEND is not null");
            return this;
        }

        public Criteria andExtendEqualTo(String value) {
            addCriterion("EXTEND =", value, "extend");
            return this;
        }

        public Criteria andExtendNotEqualTo(String value) {
            addCriterion("EXTEND <>", value, "extend");
            return this;
        }

        public Criteria andExtendGreaterThan(String value) {
            addCriterion("EXTEND >", value, "extend");
            return this;
        }

        public Criteria andExtendGreaterThanOrEqualTo(String value) {
            addCriterion("EXTEND >=", value, "extend");
            return this;
        }

        public Criteria andExtendLessThan(String value) {
            addCriterion("EXTEND <", value, "extend");
            return this;
        }

        public Criteria andExtendLessThanOrEqualTo(String value) {
            addCriterion("EXTEND <=", value, "extend");
            return this;
        }

        public Criteria andExtendLike(String value) {
            addCriterion("EXTEND like", value, "extend");
            return this;
        }

        public Criteria andExtendNotLike(String value) {
            addCriterion("EXTEND not like", value, "extend");
            return this;
        }

        public Criteria andExtendIn(List values) {
            addCriterion("EXTEND in", values, "extend");
            return this;
        }

        public Criteria andExtendNotIn(List values) {
            addCriterion("EXTEND not in", values, "extend");
            return this;
        }

        public Criteria andExtendBetween(String value1, String value2) {
            addCriterion("EXTEND between", value1, value2, "extend");
            return this;
        }

        public Criteria andExtendNotBetween(String value1, String value2) {
            addCriterion("EXTEND not between", value1, value2, "extend");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andAgreeClauseIsNull() {
            addCriterion("AGREE_CLAUSE is null");
            return this;
        }

        public Criteria andAgreeClauseIsNotNull() {
            addCriterion("AGREE_CLAUSE is not null");
            return this;
        }

        public Criteria andAgreeClauseEqualTo(Integer value) {
            addCriterion("AGREE_CLAUSE =", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseNotEqualTo(Integer value) {
            addCriterion("AGREE_CLAUSE <>", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseGreaterThan(Integer value) {
            addCriterion("AGREE_CLAUSE >", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGREE_CLAUSE >=", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseLessThan(Integer value) {
            addCriterion("AGREE_CLAUSE <", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseLessThanOrEqualTo(Integer value) {
            addCriterion("AGREE_CLAUSE <=", value, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseIn(List values) {
            addCriterion("AGREE_CLAUSE in", values, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseNotIn(List values) {
            addCriterion("AGREE_CLAUSE not in", values, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseBetween(Integer value1, Integer value2) {
            addCriterion("AGREE_CLAUSE between", value1, value2, "agreeClause");
            return this;
        }

        public Criteria andAgreeClauseNotBetween(Integer value1, Integer value2) {
            addCriterion("AGREE_CLAUSE not between", value1, value2, "agreeClause");
            return this;
        }

        public Criteria andParentOrderSnIsNull() {
            addCriterion("PARENT_ORDER_SN is null");
            return this;
        }

        public Criteria andParentOrderSnIsNotNull() {
            addCriterion("PARENT_ORDER_SN is not null");
            return this;
        }

        public Criteria andParentOrderSnEqualTo(Long value) {
            addCriterion("PARENT_ORDER_SN =", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnNotEqualTo(Long value) {
            addCriterion("PARENT_ORDER_SN <>", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnGreaterThan(Long value) {
            addCriterion("PARENT_ORDER_SN >", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENT_ORDER_SN >=", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnLessThan(Long value) {
            addCriterion("PARENT_ORDER_SN <", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnLessThanOrEqualTo(Long value) {
            addCriterion("PARENT_ORDER_SN <=", value, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnIn(List values) {
            addCriterion("PARENT_ORDER_SN in", values, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnNotIn(List values) {
            addCriterion("PARENT_ORDER_SN not in", values, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnBetween(Long value1, Long value2) {
            addCriterion("PARENT_ORDER_SN between", value1, value2, "parentOrderSn");
            return this;
        }

        public Criteria andParentOrderSnNotBetween(Long value1, Long value2) {
            addCriterion("PARENT_ORDER_SN not between", value1, value2, "parentOrderSn");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}