package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_bm_role_resource", Class = PanoBmRoleResource.class)
public class PanoBmRoleResource<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Long roleSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.RESOURCE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Long resourceSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_USER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_BASICS
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleBasics;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_PRODUCT
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleProduct;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_HOUSES
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleHouses;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_ROLE
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleRole;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.ROLE_ORDER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private Integer roleOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_bm_role_resource.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.SN
     *
     * @return the value of pano_bm_role_resource.SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.SN
     *
     * @param sn the value for pano_bm_role_resource.SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_SN
     *
     * @return the value of pano_bm_role_resource.ROLE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Long getRoleSn() {
        return roleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_SN
     *
     * @param roleSn the value for pano_bm_role_resource.ROLE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleSn(Long roleSn) {
        this.roleSn = roleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.RESOURCE_SN
     *
     * @return the value of pano_bm_role_resource.RESOURCE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Long getResourceSn() {
        return resourceSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.RESOURCE_SN
     *
     * @param resourceSn the value for pano_bm_role_resource.RESOURCE_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setResourceSn(Long resourceSn) {
        this.resourceSn = resourceSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ADDER_SN
     *
     * @return the value of pano_bm_role_resource.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ADDER_SN
     *
     * @param adderSn the value for pano_bm_role_resource.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ADDER_NAME
     *
     * @return the value of pano_bm_role_resource.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ADDER_NAME
     *
     * @param adderName the value for pano_bm_role_resource.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ADD_TIME
     *
     * @return the value of pano_bm_role_resource.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ADD_TIME
     *
     * @param addTime the value for pano_bm_role_resource.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.UPDATER_SN
     *
     * @return the value of pano_bm_role_resource.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.UPDATER_SN
     *
     * @param updaterSn the value for pano_bm_role_resource.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.UPDATER_NAME
     *
     * @return the value of pano_bm_role_resource.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.UPDATER_NAME
     *
     * @param updaterName the value for pano_bm_role_resource.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.UPDATE_TIME
     *
     * @return the value of pano_bm_role_resource.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.UPDATE_TIME
     *
     * @param updateTime the value for pano_bm_role_resource.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_USER
     *
     * @return the value of pano_bm_role_resource.ROLE_USER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleUser() {
        return roleUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_USER
     *
     * @param roleUser the value for pano_bm_role_resource.ROLE_USER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleUser(Integer roleUser) {
        this.roleUser = roleUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_BASICS
     *
     * @return the value of pano_bm_role_resource.ROLE_BASICS
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleBasics() {
        return roleBasics;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_BASICS
     *
     * @param roleBasics the value for pano_bm_role_resource.ROLE_BASICS
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleBasics(Integer roleBasics) {
        this.roleBasics = roleBasics;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_PRODUCT
     *
     * @return the value of pano_bm_role_resource.ROLE_PRODUCT
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleProduct() {
        return roleProduct;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_PRODUCT
     *
     * @param roleProduct the value for pano_bm_role_resource.ROLE_PRODUCT
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleProduct(Integer roleProduct) {
        this.roleProduct = roleProduct;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_HOUSES
     *
     * @return the value of pano_bm_role_resource.ROLE_HOUSES
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleHouses() {
        return roleHouses;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_HOUSES
     *
     * @param roleHouses the value for pano_bm_role_resource.ROLE_HOUSES
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleHouses(Integer roleHouses) {
        this.roleHouses = roleHouses;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_ROLE
     *
     * @return the value of pano_bm_role_resource.ROLE_ROLE
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleRole() {
        return roleRole;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_ROLE
     *
     * @param roleRole the value for pano_bm_role_resource.ROLE_ROLE
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleRole(Integer roleRole) {
        this.roleRole = roleRole;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.ROLE_ORDER
     *
     * @return the value of pano_bm_role_resource.ROLE_ORDER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public Integer getRoleOrder() {
        return roleOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.ROLE_ORDER
     *
     * @param roleOrder the value for pano_bm_role_resource.ROLE_ORDER
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setRoleOrder(Integer roleOrder) {
        this.roleOrder = roleOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_bm_role_resource.encryptSn
     *
     * @return the value of pano_bm_role_resource.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_bm_role_resource.encryptSn
     *
     * @param encryptSn the value for pano_bm_role_resource.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 21:55:48 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}