package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_perspective_view", Class = PanoPerspectiveView.class)
public class PanoPerspectiveView<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.VIEW_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String viewName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.BASE_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long baseMap;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long houseStyleSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.HOUSE_SPACE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long houseSpaceSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.VIEW_ORDER
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private Integer viewOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_perspective_view.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.SN
     *
     * @return the value of pano_perspective_view.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.SN
     *
     * @param sn the value for pano_perspective_view.SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.VIEW_NAME
     *
     * @return the value of pano_perspective_view.VIEW_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.VIEW_NAME
     *
     * @param viewName the value for pano_perspective_view.VIEW_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setViewName(String viewName) {
        this.viewName = viewName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.BASE_MAP
     *
     * @return the value of pano_perspective_view.BASE_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getBaseMap() {
        return baseMap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.BASE_MAP
     *
     * @param baseMap the value for pano_perspective_view.BASE_MAP
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setBaseMap(Long baseMap) {
        this.baseMap = baseMap;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.HOUSE_STYLE_SN
     *
     * @return the value of pano_perspective_view.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getHouseStyleSn() {
        return houseStyleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.HOUSE_STYLE_SN
     *
     * @param houseStyleSn the value for pano_perspective_view.HOUSE_STYLE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setHouseStyleSn(Long houseStyleSn) {
        this.houseStyleSn = houseStyleSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.HOUSE_SPACE_SN
     *
     * @return the value of pano_perspective_view.HOUSE_SPACE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getHouseSpaceSn() {
        return houseSpaceSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.HOUSE_SPACE_SN
     *
     * @param houseSpaceSn the value for pano_perspective_view.HOUSE_SPACE_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setHouseSpaceSn(Long houseSpaceSn) {
        this.houseSpaceSn = houseSpaceSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.ADDER_SN
     *
     * @return the value of pano_perspective_view.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.ADDER_SN
     *
     * @param adderSn the value for pano_perspective_view.ADDER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.ADDER_NAME
     *
     * @return the value of pano_perspective_view.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.ADDER_NAME
     *
     * @param adderName the value for pano_perspective_view.ADDER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.ADD_TIME
     *
     * @return the value of pano_perspective_view.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.ADD_TIME
     *
     * @param addTime the value for pano_perspective_view.ADD_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.UPDATER_SN
     *
     * @return the value of pano_perspective_view.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.UPDATER_SN
     *
     * @param updaterSn the value for pano_perspective_view.UPDATER_SN
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.UPDATER_NAME
     *
     * @return the value of pano_perspective_view.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.UPDATER_NAME
     *
     * @param updaterName the value for pano_perspective_view.UPDATER_NAME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.UPDATE_TIME
     *
     * @return the value of pano_perspective_view.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.UPDATE_TIME
     *
     * @param updateTime the value for pano_perspective_view.UPDATE_TIME
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.VIEW_ORDER
     *
     * @return the value of pano_perspective_view.VIEW_ORDER
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public Integer getViewOrder() {
        return viewOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.VIEW_ORDER
     *
     * @param viewOrder the value for pano_perspective_view.VIEW_ORDER
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setViewOrder(Integer viewOrder) {
        this.viewOrder = viewOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_perspective_view.encryptSn
     *
     * @return the value of pano_perspective_view.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_perspective_view.encryptSn
     *
     * @param encryptSn the value for pano_perspective_view.encryptSn
     *
     * @ibatorgenerated Sun Aug 20 22:36:51 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}