package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "pano_order_coupon_item", Class = PanoOrderCouponItem.class)
public class PanoOrderCouponItemCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public PanoOrderCouponItemCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public PanoOrderCouponItemCriteria(PanoOrderCouponItemCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public PanoOrderCouponItemCriteria(Object record, PanoOrderCouponItemCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pano_order_coupon_item
     *
     * @ibatorgenerated Fri Aug 25 14:59:35 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andCouponSnIsNull() {
            addCriterion("COUPON_SN is null");
            return this;
        }

        public Criteria andCouponSnIsNotNull() {
            addCriterion("COUPON_SN is not null");
            return this;
        }

        public Criteria andCouponSnEqualTo(Long value) {
            addCriterion("COUPON_SN =", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnNotEqualTo(Long value) {
            addCriterion("COUPON_SN <>", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnGreaterThan(Long value) {
            addCriterion("COUPON_SN >", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnGreaterThanOrEqualTo(Long value) {
            addCriterion("COUPON_SN >=", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnLessThan(Long value) {
            addCriterion("COUPON_SN <", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnLessThanOrEqualTo(Long value) {
            addCriterion("COUPON_SN <=", value, "couponSn");
            return this;
        }

        public Criteria andCouponSnIn(List values) {
            addCriterion("COUPON_SN in", values, "couponSn");
            return this;
        }

        public Criteria andCouponSnNotIn(List values) {
            addCriterion("COUPON_SN not in", values, "couponSn");
            return this;
        }

        public Criteria andCouponSnBetween(Long value1, Long value2) {
            addCriterion("COUPON_SN between", value1, value2, "couponSn");
            return this;
        }

        public Criteria andCouponSnNotBetween(Long value1, Long value2) {
            addCriterion("COUPON_SN not between", value1, value2, "couponSn");
            return this;
        }

        public Criteria andCodeNumIsNull() {
            addCriterion("CODE_NUM is null");
            return this;
        }

        public Criteria andCodeNumIsNotNull() {
            addCriterion("CODE_NUM is not null");
            return this;
        }

        public Criteria andCodeNumEqualTo(String value) {
            addCriterion("CODE_NUM =", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumNotEqualTo(String value) {
            addCriterion("CODE_NUM <>", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumGreaterThan(String value) {
            addCriterion("CODE_NUM >", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_NUM >=", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumLessThan(String value) {
            addCriterion("CODE_NUM <", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumLessThanOrEqualTo(String value) {
            addCriterion("CODE_NUM <=", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumLike(String value) {
            addCriterion("CODE_NUM like", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumNotLike(String value) {
            addCriterion("CODE_NUM not like", value, "codeNum");
            return this;
        }

        public Criteria andCodeNumIn(List values) {
            addCriterion("CODE_NUM in", values, "codeNum");
            return this;
        }

        public Criteria andCodeNumNotIn(List values) {
            addCriterion("CODE_NUM not in", values, "codeNum");
            return this;
        }

        public Criteria andCodeNumBetween(String value1, String value2) {
            addCriterion("CODE_NUM between", value1, value2, "codeNum");
            return this;
        }

        public Criteria andCodeNumNotBetween(String value1, String value2) {
            addCriterion("CODE_NUM not between", value1, value2, "codeNum");
            return this;
        }

        public Criteria andCodeStatusIsNull() {
            addCriterion("CODE_STATUS is null");
            return this;
        }

        public Criteria andCodeStatusIsNotNull() {
            addCriterion("CODE_STATUS is not null");
            return this;
        }

        public Criteria andCodeStatusEqualTo(Integer value) {
            addCriterion("CODE_STATUS =", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusNotEqualTo(Integer value) {
            addCriterion("CODE_STATUS <>", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusGreaterThan(Integer value) {
            addCriterion("CODE_STATUS >", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("CODE_STATUS >=", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusLessThan(Integer value) {
            addCriterion("CODE_STATUS <", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("CODE_STATUS <=", value, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusIn(List values) {
            addCriterion("CODE_STATUS in", values, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusNotIn(List values) {
            addCriterion("CODE_STATUS not in", values, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusBetween(Integer value1, Integer value2) {
            addCriterion("CODE_STATUS between", value1, value2, "codeStatus");
            return this;
        }

        public Criteria andCodeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("CODE_STATUS not between", value1, value2, "codeStatus");
            return this;
        }

        public Criteria andUserSnIsNull() {
            addCriterion("user_sn is null");
            return this;
        }

        public Criteria andUserSnIsNotNull() {
            addCriterion("user_sn is not null");
            return this;
        }

        public Criteria andUserSnEqualTo(Long value) {
            addCriterion("user_sn =", value, "userSn");
            return this;
        }

        public Criteria andUserSnNotEqualTo(Long value) {
            addCriterion("user_sn <>", value, "userSn");
            return this;
        }

        public Criteria andUserSnGreaterThan(Long value) {
            addCriterion("user_sn >", value, "userSn");
            return this;
        }

        public Criteria andUserSnGreaterThanOrEqualTo(Long value) {
            addCriterion("user_sn >=", value, "userSn");
            return this;
        }

        public Criteria andUserSnLessThan(Long value) {
            addCriterion("user_sn <", value, "userSn");
            return this;
        }

        public Criteria andUserSnLessThanOrEqualTo(Long value) {
            addCriterion("user_sn <=", value, "userSn");
            return this;
        }

        public Criteria andUserSnIn(List values) {
            addCriterion("user_sn in", values, "userSn");
            return this;
        }

        public Criteria andUserSnNotIn(List values) {
            addCriterion("user_sn not in", values, "userSn");
            return this;
        }

        public Criteria andUserSnBetween(Long value1, Long value2) {
            addCriterion("user_sn between", value1, value2, "userSn");
            return this;
        }

        public Criteria andUserSnNotBetween(Long value1, Long value2) {
            addCriterion("user_sn not between", value1, value2, "userSn");
            return this;
        }

        public Criteria andOrderSnIsNull() {
            addCriterion("order_sn is null");
            return this;
        }

        public Criteria andOrderSnIsNotNull() {
            addCriterion("order_sn is not null");
            return this;
        }

        public Criteria andOrderSnEqualTo(Long value) {
            addCriterion("order_sn =", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnNotEqualTo(Long value) {
            addCriterion("order_sn <>", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnGreaterThan(Long value) {
            addCriterion("order_sn >", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("order_sn >=", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnLessThan(Long value) {
            addCriterion("order_sn <", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnLessThanOrEqualTo(Long value) {
            addCriterion("order_sn <=", value, "orderSn");
            return this;
        }

        public Criteria andOrderSnIn(List values) {
            addCriterion("order_sn in", values, "orderSn");
            return this;
        }

        public Criteria andOrderSnNotIn(List values) {
            addCriterion("order_sn not in", values, "orderSn");
            return this;
        }

        public Criteria andOrderSnBetween(Long value1, Long value2) {
            addCriterion("order_sn between", value1, value2, "orderSn");
            return this;
        }

        public Criteria andOrderSnNotBetween(Long value1, Long value2) {
            addCriterion("order_sn not between", value1, value2, "orderSn");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }
    }
}