package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.Column;
import com.focustech.cief.ibatis.annotation.PrimaryKey;
import com.focustech.cief.ibatis.annotation.SqlMap;
import com.focustech.cief.ibatis.annotation.Xss;
import java.math.BigDecimal;
import java.util.Date;

@Xss
@SqlMap(Name = "pano_order_coupon", Class = PanoOrderCoupon.class)
public class PanoOrderCoupon<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @PrimaryKey
    @Column
    private Long sn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Long projectSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.PRICE_DISCOUNT
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private BigDecimal priceDiscount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.START_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Date startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.END_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.NUM
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Integer num;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.STATUS
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Long adderSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private String adderName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Long updaterSn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private String updaterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pano_order_coupon.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    @Column
    private String encryptSn;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.SN
     *
     * @return the value of pano_order_coupon.SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Long getSn() {
        return sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.SN
     *
     * @param sn the value for pano_order_coupon.SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setSn(Long sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.PROJECT_SN
     *
     * @return the value of pano_order_coupon.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Long getProjectSn() {
        return projectSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.PROJECT_SN
     *
     * @param projectSn the value for pano_order_coupon.PROJECT_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setProjectSn(Long projectSn) {
        this.projectSn = projectSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.PRICE_DISCOUNT
     *
     * @return the value of pano_order_coupon.PRICE_DISCOUNT
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public BigDecimal getPriceDiscount() {
        return priceDiscount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.PRICE_DISCOUNT
     *
     * @param priceDiscount the value for pano_order_coupon.PRICE_DISCOUNT
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setPriceDiscount(BigDecimal priceDiscount) {
        this.priceDiscount = priceDiscount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.START_DATE
     *
     * @return the value of pano_order_coupon.START_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.START_DATE
     *
     * @param startDate the value for pano_order_coupon.START_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.END_DATE
     *
     * @return the value of pano_order_coupon.END_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.END_DATE
     *
     * @param endDate the value for pano_order_coupon.END_DATE
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.NUM
     *
     * @return the value of pano_order_coupon.NUM
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.NUM
     *
     * @param num the value for pano_order_coupon.NUM
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.STATUS
     *
     * @return the value of pano_order_coupon.STATUS
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.STATUS
     *
     * @param status the value for pano_order_coupon.STATUS
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.ADDER_SN
     *
     * @return the value of pano_order_coupon.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Long getAdderSn() {
        return adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.ADDER_SN
     *
     * @param adderSn the value for pano_order_coupon.ADDER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setAdderSn(Long adderSn) {
        this.adderSn = adderSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.ADDER_NAME
     *
     * @return the value of pano_order_coupon.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public String getAdderName() {
        return adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.ADDER_NAME
     *
     * @param adderName the value for pano_order_coupon.ADDER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setAdderName(String adderName) {
        this.adderName = adderName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.ADD_TIME
     *
     * @return the value of pano_order_coupon.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.ADD_TIME
     *
     * @param addTime the value for pano_order_coupon.ADD_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.UPDATER_SN
     *
     * @return the value of pano_order_coupon.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Long getUpdaterSn() {
        return updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.UPDATER_SN
     *
     * @param updaterSn the value for pano_order_coupon.UPDATER_SN
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setUpdaterSn(Long updaterSn) {
        this.updaterSn = updaterSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.UPDATER_NAME
     *
     * @return the value of pano_order_coupon.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.UPDATER_NAME
     *
     * @param updaterName the value for pano_order_coupon.UPDATER_NAME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.UPDATE_TIME
     *
     * @return the value of pano_order_coupon.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.UPDATE_TIME
     *
     * @param updateTime the value for pano_order_coupon.UPDATE_TIME
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pano_order_coupon.encryptSn
     *
     * @return the value of pano_order_coupon.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public String getEncryptSn() {
        return encryptSn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pano_order_coupon.encryptSn
     *
     * @param encryptSn the value for pano_order_coupon.encryptSn
     *
     * @ibatorgenerated Fri Aug 25 20:43:33 CST 2017
     */
    public void setEncryptSn(String encryptSn) {
        this.encryptSn = encryptSn;
    }
}