package com.focus3d.pano.model.ibator;

import com.focustech.cief.ibatis.annotation.SqlMap;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SqlMap(Name = "pano_product", Class = PanoProduct.class)
public class PanoProductCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    protected Object record;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public PanoProductCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public PanoProductCriteria(PanoProductCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public PanoProductCriteria(Object record, PanoProductCriteria example) {
        this.record = record;
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pano_product
     *
     * @ibatorgenerated Thu Aug 24 18:55:26 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSnIsNull() {
            addCriterion("SN is null");
            return this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("SN is not null");
            return this;
        }

        public Criteria andSnEqualTo(Long value) {
            addCriterion("SN =", value, "sn");
            return this;
        }

        public Criteria andSnNotEqualTo(Long value) {
            addCriterion("SN <>", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThan(Long value) {
            addCriterion("SN >", value, "sn");
            return this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SN >=", value, "sn");
            return this;
        }

        public Criteria andSnLessThan(Long value) {
            addCriterion("SN <", value, "sn");
            return this;
        }

        public Criteria andSnLessThanOrEqualTo(Long value) {
            addCriterion("SN <=", value, "sn");
            return this;
        }

        public Criteria andSnIn(List values) {
            addCriterion("SN in", values, "sn");
            return this;
        }

        public Criteria andSnNotIn(List values) {
            addCriterion("SN not in", values, "sn");
            return this;
        }

        public Criteria andSnBetween(Long value1, Long value2) {
            addCriterion("SN between", value1, value2, "sn");
            return this;
        }

        public Criteria andSnNotBetween(Long value1, Long value2) {
            addCriterion("SN not between", value1, value2, "sn");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("BRAND is null");
            return this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("BRAND is not null");
            return this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("BRAND =", value, "brand");
            return this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("BRAND <>", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("BRAND >", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND >=", value, "brand");
            return this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("BRAND <", value, "brand");
            return this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("BRAND <=", value, "brand");
            return this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("BRAND like", value, "brand");
            return this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("BRAND not like", value, "brand");
            return this;
        }

        public Criteria andBrandIn(List values) {
            addCriterion("BRAND in", values, "brand");
            return this;
        }

        public Criteria andBrandNotIn(List values) {
            addCriterion("BRAND not in", values, "brand");
            return this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("BRAND between", value1, value2, "brand");
            return this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("BRAND not between", value1, value2, "brand");
            return this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("PRICE =", value, "price");
            return this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("PRICE <>", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("PRICE >", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE >=", value, "price");
            return this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("PRICE <", value, "price");
            return this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE <=", value, "price");
            return this;
        }

        public Criteria andPriceIn(List values) {
            addCriterion("PRICE in", values, "price");
            return this;
        }

        public Criteria andPriceNotIn(List values) {
            addCriterion("PRICE not in", values, "price");
            return this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return this;
        }

        public Criteria andDiscountPriceIsNull() {
            addCriterion("discount_price is null");
            return this;
        }

        public Criteria andDiscountPriceIsNotNull() {
            addCriterion("discount_price is not null");
            return this;
        }

        public Criteria andDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("discount_price =", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("discount_price <>", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("discount_price >", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price >=", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceLessThan(BigDecimal value) {
            addCriterion("discount_price <", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price <=", value, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceIn(List values) {
            addCriterion("discount_price in", values, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceNotIn(List values) {
            addCriterion("discount_price not in", values, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price between", value1, value2, "discountPrice");
            return this;
        }

        public Criteria andDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price not between", value1, value2, "discountPrice");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("SUMMARY is null");
            return this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("SUMMARY is not null");
            return this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("SUMMARY =", value, "summary");
            return this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("SUMMARY <>", value, "summary");
            return this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("SUMMARY >", value, "summary");
            return this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("SUMMARY >=", value, "summary");
            return this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("SUMMARY <", value, "summary");
            return this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("SUMMARY <=", value, "summary");
            return this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("SUMMARY like", value, "summary");
            return this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("SUMMARY not like", value, "summary");
            return this;
        }

        public Criteria andSummaryIn(List values) {
            addCriterion("SUMMARY in", values, "summary");
            return this;
        }

        public Criteria andSummaryNotIn(List values) {
            addCriterion("SUMMARY not in", values, "summary");
            return this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("SUMMARY between", value1, value2, "summary");
            return this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("SUMMARY not between", value1, value2, "summary");
            return this;
        }

        public Criteria andLeftImgSnIsNull() {
            addCriterion("LEFT_IMG_SN is null");
            return this;
        }

        public Criteria andLeftImgSnIsNotNull() {
            addCriterion("LEFT_IMG_SN is not null");
            return this;
        }

        public Criteria andLeftImgSnEqualTo(Long value) {
            addCriterion("LEFT_IMG_SN =", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnNotEqualTo(Long value) {
            addCriterion("LEFT_IMG_SN <>", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnGreaterThan(Long value) {
            addCriterion("LEFT_IMG_SN >", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("LEFT_IMG_SN >=", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnLessThan(Long value) {
            addCriterion("LEFT_IMG_SN <", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnLessThanOrEqualTo(Long value) {
            addCriterion("LEFT_IMG_SN <=", value, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnIn(List values) {
            addCriterion("LEFT_IMG_SN in", values, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnNotIn(List values) {
            addCriterion("LEFT_IMG_SN not in", values, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnBetween(Long value1, Long value2) {
            addCriterion("LEFT_IMG_SN between", value1, value2, "leftImgSn");
            return this;
        }

        public Criteria andLeftImgSnNotBetween(Long value1, Long value2) {
            addCriterion("LEFT_IMG_SN not between", value1, value2, "leftImgSn");
            return this;
        }

        public Criteria andDownImgSnIsNull() {
            addCriterion("DOWN_IMG_SN is null");
            return this;
        }

        public Criteria andDownImgSnIsNotNull() {
            addCriterion("DOWN_IMG_SN is not null");
            return this;
        }

        public Criteria andDownImgSnEqualTo(Long value) {
            addCriterion("DOWN_IMG_SN =", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnNotEqualTo(Long value) {
            addCriterion("DOWN_IMG_SN <>", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnGreaterThan(Long value) {
            addCriterion("DOWN_IMG_SN >", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("DOWN_IMG_SN >=", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnLessThan(Long value) {
            addCriterion("DOWN_IMG_SN <", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnLessThanOrEqualTo(Long value) {
            addCriterion("DOWN_IMG_SN <=", value, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnIn(List values) {
            addCriterion("DOWN_IMG_SN in", values, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnNotIn(List values) {
            addCriterion("DOWN_IMG_SN not in", values, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnBetween(Long value1, Long value2) {
            addCriterion("DOWN_IMG_SN between", value1, value2, "downImgSn");
            return this;
        }

        public Criteria andDownImgSnNotBetween(Long value1, Long value2) {
            addCriterion("DOWN_IMG_SN not between", value1, value2, "downImgSn");
            return this;
        }

        public Criteria andFullImgSnIsNull() {
            addCriterion("FULL_IMG_SN is null");
            return this;
        }

        public Criteria andFullImgSnIsNotNull() {
            addCriterion("FULL_IMG_SN is not null");
            return this;
        }

        public Criteria andFullImgSnEqualTo(Long value) {
            addCriterion("FULL_IMG_SN =", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnNotEqualTo(Long value) {
            addCriterion("FULL_IMG_SN <>", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnGreaterThan(Long value) {
            addCriterion("FULL_IMG_SN >", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("FULL_IMG_SN >=", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnLessThan(Long value) {
            addCriterion("FULL_IMG_SN <", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnLessThanOrEqualTo(Long value) {
            addCriterion("FULL_IMG_SN <=", value, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnIn(List values) {
            addCriterion("FULL_IMG_SN in", values, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnNotIn(List values) {
            addCriterion("FULL_IMG_SN not in", values, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnBetween(Long value1, Long value2) {
            addCriterion("FULL_IMG_SN between", value1, value2, "fullImgSn");
            return this;
        }

        public Criteria andFullImgSnNotBetween(Long value1, Long value2) {
            addCriterion("FULL_IMG_SN not between", value1, value2, "fullImgSn");
            return this;
        }

        public Criteria andBannerImgSnIsNull() {
            addCriterion("BANNER_IMG_SN is null");
            return this;
        }

        public Criteria andBannerImgSnIsNotNull() {
            addCriterion("BANNER_IMG_SN is not null");
            return this;
        }

        public Criteria andBannerImgSnEqualTo(Long value) {
            addCriterion("BANNER_IMG_SN =", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnNotEqualTo(Long value) {
            addCriterion("BANNER_IMG_SN <>", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnGreaterThan(Long value) {
            addCriterion("BANNER_IMG_SN >", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("BANNER_IMG_SN >=", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnLessThan(Long value) {
            addCriterion("BANNER_IMG_SN <", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnLessThanOrEqualTo(Long value) {
            addCriterion("BANNER_IMG_SN <=", value, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnIn(List values) {
            addCriterion("BANNER_IMG_SN in", values, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnNotIn(List values) {
            addCriterion("BANNER_IMG_SN not in", values, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnBetween(Long value1, Long value2) {
            addCriterion("BANNER_IMG_SN between", value1, value2, "bannerImgSn");
            return this;
        }

        public Criteria andBannerImgSnNotBetween(Long value1, Long value2) {
            addCriterion("BANNER_IMG_SN not between", value1, value2, "bannerImgSn");
            return this;
        }

        public Criteria andTypeSnIsNull() {
            addCriterion("TYPE_SN is null");
            return this;
        }

        public Criteria andTypeSnIsNotNull() {
            addCriterion("TYPE_SN is not null");
            return this;
        }

        public Criteria andTypeSnEqualTo(Long value) {
            addCriterion("TYPE_SN =", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnNotEqualTo(Long value) {
            addCriterion("TYPE_SN <>", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnGreaterThan(Long value) {
            addCriterion("TYPE_SN >", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnGreaterThanOrEqualTo(Long value) {
            addCriterion("TYPE_SN >=", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnLessThan(Long value) {
            addCriterion("TYPE_SN <", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnLessThanOrEqualTo(Long value) {
            addCriterion("TYPE_SN <=", value, "typeSn");
            return this;
        }

        public Criteria andTypeSnIn(List values) {
            addCriterion("TYPE_SN in", values, "typeSn");
            return this;
        }

        public Criteria andTypeSnNotIn(List values) {
            addCriterion("TYPE_SN not in", values, "typeSn");
            return this;
        }

        public Criteria andTypeSnBetween(Long value1, Long value2) {
            addCriterion("TYPE_SN between", value1, value2, "typeSn");
            return this;
        }

        public Criteria andTypeSnNotBetween(Long value1, Long value2) {
            addCriterion("TYPE_SN not between", value1, value2, "typeSn");
            return this;
        }

        public Criteria andFuncSnIsNull() {
            addCriterion("FUNC_SN is null");
            return this;
        }

        public Criteria andFuncSnIsNotNull() {
            addCriterion("FUNC_SN is not null");
            return this;
        }

        public Criteria andFuncSnEqualTo(Long value) {
            addCriterion("FUNC_SN =", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnNotEqualTo(Long value) {
            addCriterion("FUNC_SN <>", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnGreaterThan(Long value) {
            addCriterion("FUNC_SN >", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnGreaterThanOrEqualTo(Long value) {
            addCriterion("FUNC_SN >=", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnLessThan(Long value) {
            addCriterion("FUNC_SN <", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnLessThanOrEqualTo(Long value) {
            addCriterion("FUNC_SN <=", value, "funcSn");
            return this;
        }

        public Criteria andFuncSnIn(List values) {
            addCriterion("FUNC_SN in", values, "funcSn");
            return this;
        }

        public Criteria andFuncSnNotIn(List values) {
            addCriterion("FUNC_SN not in", values, "funcSn");
            return this;
        }

        public Criteria andFuncSnBetween(Long value1, Long value2) {
            addCriterion("FUNC_SN between", value1, value2, "funcSn");
            return this;
        }

        public Criteria andFuncSnNotBetween(Long value1, Long value2) {
            addCriterion("FUNC_SN not between", value1, value2, "funcSn");
            return this;
        }

        public Criteria andSpaceSnIsNull() {
            addCriterion("SPACE_SN is null");
            return this;
        }

        public Criteria andSpaceSnIsNotNull() {
            addCriterion("SPACE_SN is not null");
            return this;
        }

        public Criteria andSpaceSnEqualTo(Long value) {
            addCriterion("SPACE_SN =", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnNotEqualTo(Long value) {
            addCriterion("SPACE_SN <>", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnGreaterThan(Long value) {
            addCriterion("SPACE_SN >", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnGreaterThanOrEqualTo(Long value) {
            addCriterion("SPACE_SN >=", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnLessThan(Long value) {
            addCriterion("SPACE_SN <", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnLessThanOrEqualTo(Long value) {
            addCriterion("SPACE_SN <=", value, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnIn(List values) {
            addCriterion("SPACE_SN in", values, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnNotIn(List values) {
            addCriterion("SPACE_SN not in", values, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnBetween(Long value1, Long value2) {
            addCriterion("SPACE_SN between", value1, value2, "spaceSn");
            return this;
        }

        public Criteria andSpaceSnNotBetween(Long value1, Long value2) {
            addCriterion("SPACE_SN not between", value1, value2, "spaceSn");
            return this;
        }

        public Criteria andStyleSnIsNull() {
            addCriterion("STYLE_SN is null");
            return this;
        }

        public Criteria andStyleSnIsNotNull() {
            addCriterion("STYLE_SN is not null");
            return this;
        }

        public Criteria andStyleSnEqualTo(Long value) {
            addCriterion("STYLE_SN =", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnNotEqualTo(Long value) {
            addCriterion("STYLE_SN <>", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnGreaterThan(Long value) {
            addCriterion("STYLE_SN >", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnGreaterThanOrEqualTo(Long value) {
            addCriterion("STYLE_SN >=", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnLessThan(Long value) {
            addCriterion("STYLE_SN <", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnLessThanOrEqualTo(Long value) {
            addCriterion("STYLE_SN <=", value, "styleSn");
            return this;
        }

        public Criteria andStyleSnIn(List values) {
            addCriterion("STYLE_SN in", values, "styleSn");
            return this;
        }

        public Criteria andStyleSnNotIn(List values) {
            addCriterion("STYLE_SN not in", values, "styleSn");
            return this;
        }

        public Criteria andStyleSnBetween(Long value1, Long value2) {
            addCriterion("STYLE_SN between", value1, value2, "styleSn");
            return this;
        }

        public Criteria andStyleSnNotBetween(Long value1, Long value2) {
            addCriterion("STYLE_SN not between", value1, value2, "styleSn");
            return this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("LENGTH is null");
            return this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("LENGTH is not null");
            return this;
        }

        public Criteria andLengthEqualTo(Integer value) {
            addCriterion("LENGTH =", value, "length");
            return this;
        }

        public Criteria andLengthNotEqualTo(Integer value) {
            addCriterion("LENGTH <>", value, "length");
            return this;
        }

        public Criteria andLengthGreaterThan(Integer value) {
            addCriterion("LENGTH >", value, "length");
            return this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("LENGTH >=", value, "length");
            return this;
        }

        public Criteria andLengthLessThan(Integer value) {
            addCriterion("LENGTH <", value, "length");
            return this;
        }

        public Criteria andLengthLessThanOrEqualTo(Integer value) {
            addCriterion("LENGTH <=", value, "length");
            return this;
        }

        public Criteria andLengthIn(List values) {
            addCriterion("LENGTH in", values, "length");
            return this;
        }

        public Criteria andLengthNotIn(List values) {
            addCriterion("LENGTH not in", values, "length");
            return this;
        }

        public Criteria andLengthBetween(Integer value1, Integer value2) {
            addCriterion("LENGTH between", value1, value2, "length");
            return this;
        }

        public Criteria andLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("LENGTH not between", value1, value2, "length");
            return this;
        }

        public Criteria andWideIsNull() {
            addCriterion("WIDE is null");
            return this;
        }

        public Criteria andWideIsNotNull() {
            addCriterion("WIDE is not null");
            return this;
        }

        public Criteria andWideEqualTo(Integer value) {
            addCriterion("WIDE =", value, "wide");
            return this;
        }

        public Criteria andWideNotEqualTo(Integer value) {
            addCriterion("WIDE <>", value, "wide");
            return this;
        }

        public Criteria andWideGreaterThan(Integer value) {
            addCriterion("WIDE >", value, "wide");
            return this;
        }

        public Criteria andWideGreaterThanOrEqualTo(Integer value) {
            addCriterion("WIDE >=", value, "wide");
            return this;
        }

        public Criteria andWideLessThan(Integer value) {
            addCriterion("WIDE <", value, "wide");
            return this;
        }

        public Criteria andWideLessThanOrEqualTo(Integer value) {
            addCriterion("WIDE <=", value, "wide");
            return this;
        }

        public Criteria andWideIn(List values) {
            addCriterion("WIDE in", values, "wide");
            return this;
        }

        public Criteria andWideNotIn(List values) {
            addCriterion("WIDE not in", values, "wide");
            return this;
        }

        public Criteria andWideBetween(Integer value1, Integer value2) {
            addCriterion("WIDE between", value1, value2, "wide");
            return this;
        }

        public Criteria andWideNotBetween(Integer value1, Integer value2) {
            addCriterion("WIDE not between", value1, value2, "wide");
            return this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("HEIGHT is null");
            return this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("HEIGHT is not null");
            return this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("HEIGHT =", value, "height");
            return this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("HEIGHT <>", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("HEIGHT >", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("HEIGHT >=", value, "height");
            return this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("HEIGHT <", value, "height");
            return this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("HEIGHT <=", value, "height");
            return this;
        }

        public Criteria andHeightIn(List values) {
            addCriterion("HEIGHT in", values, "height");
            return this;
        }

        public Criteria andHeightNotIn(List values) {
            addCriterion("HEIGHT not in", values, "height");
            return this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("HEIGHT between", value1, value2, "height");
            return this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("HEIGHT not between", value1, value2, "height");
            return this;
        }

        public Criteria andMaterialNameIsNull() {
            addCriterion("MATERIAL_NAME is null");
            return this;
        }

        public Criteria andMaterialNameIsNotNull() {
            addCriterion("MATERIAL_NAME is not null");
            return this;
        }

        public Criteria andMaterialNameEqualTo(String value) {
            addCriterion("MATERIAL_NAME =", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameNotEqualTo(String value) {
            addCriterion("MATERIAL_NAME <>", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameGreaterThan(String value) {
            addCriterion("MATERIAL_NAME >", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_NAME >=", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameLessThan(String value) {
            addCriterion("MATERIAL_NAME <", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_NAME <=", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameLike(String value) {
            addCriterion("MATERIAL_NAME like", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameNotLike(String value) {
            addCriterion("MATERIAL_NAME not like", value, "materialName");
            return this;
        }

        public Criteria andMaterialNameIn(List values) {
            addCriterion("MATERIAL_NAME in", values, "materialName");
            return this;
        }

        public Criteria andMaterialNameNotIn(List values) {
            addCriterion("MATERIAL_NAME not in", values, "materialName");
            return this;
        }

        public Criteria andMaterialNameBetween(String value1, String value2) {
            addCriterion("MATERIAL_NAME between", value1, value2, "materialName");
            return this;
        }

        public Criteria andMaterialNameNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_NAME not between", value1, value2, "materialName");
            return this;
        }

        public Criteria andMaterialColorIsNull() {
            addCriterion("MATERIAL_COLOR is null");
            return this;
        }

        public Criteria andMaterialColorIsNotNull() {
            addCriterion("MATERIAL_COLOR is not null");
            return this;
        }

        public Criteria andMaterialColorEqualTo(String value) {
            addCriterion("MATERIAL_COLOR =", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorNotEqualTo(String value) {
            addCriterion("MATERIAL_COLOR <>", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorGreaterThan(String value) {
            addCriterion("MATERIAL_COLOR >", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_COLOR >=", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorLessThan(String value) {
            addCriterion("MATERIAL_COLOR <", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_COLOR <=", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorLike(String value) {
            addCriterion("MATERIAL_COLOR like", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorNotLike(String value) {
            addCriterion("MATERIAL_COLOR not like", value, "materialColor");
            return this;
        }

        public Criteria andMaterialColorIn(List values) {
            addCriterion("MATERIAL_COLOR in", values, "materialColor");
            return this;
        }

        public Criteria andMaterialColorNotIn(List values) {
            addCriterion("MATERIAL_COLOR not in", values, "materialColor");
            return this;
        }

        public Criteria andMaterialColorBetween(String value1, String value2) {
            addCriterion("MATERIAL_COLOR between", value1, value2, "materialColor");
            return this;
        }

        public Criteria andMaterialColorNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_COLOR not between", value1, value2, "materialColor");
            return this;
        }

        public Criteria andMaterialImgSnIsNull() {
            addCriterion("MATERIAL_IMG_SN is null");
            return this;
        }

        public Criteria andMaterialImgSnIsNotNull() {
            addCriterion("MATERIAL_IMG_SN is not null");
            return this;
        }

        public Criteria andMaterialImgSnEqualTo(Long value) {
            addCriterion("MATERIAL_IMG_SN =", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnNotEqualTo(Long value) {
            addCriterion("MATERIAL_IMG_SN <>", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnGreaterThan(Long value) {
            addCriterion("MATERIAL_IMG_SN >", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("MATERIAL_IMG_SN >=", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnLessThan(Long value) {
            addCriterion("MATERIAL_IMG_SN <", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnLessThanOrEqualTo(Long value) {
            addCriterion("MATERIAL_IMG_SN <=", value, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnIn(List values) {
            addCriterion("MATERIAL_IMG_SN in", values, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnNotIn(List values) {
            addCriterion("MATERIAL_IMG_SN not in", values, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnBetween(Long value1, Long value2) {
            addCriterion("MATERIAL_IMG_SN between", value1, value2, "materialImgSn");
            return this;
        }

        public Criteria andMaterialImgSnNotBetween(Long value1, Long value2) {
            addCriterion("MATERIAL_IMG_SN not between", value1, value2, "materialImgSn");
            return this;
        }

        public Criteria andFabricNameIsNull() {
            addCriterion("FABRIC_NAME is null");
            return this;
        }

        public Criteria andFabricNameIsNotNull() {
            addCriterion("FABRIC_NAME is not null");
            return this;
        }

        public Criteria andFabricNameEqualTo(String value) {
            addCriterion("FABRIC_NAME =", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameNotEqualTo(String value) {
            addCriterion("FABRIC_NAME <>", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameGreaterThan(String value) {
            addCriterion("FABRIC_NAME >", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameGreaterThanOrEqualTo(String value) {
            addCriterion("FABRIC_NAME >=", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameLessThan(String value) {
            addCriterion("FABRIC_NAME <", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameLessThanOrEqualTo(String value) {
            addCriterion("FABRIC_NAME <=", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameLike(String value) {
            addCriterion("FABRIC_NAME like", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameNotLike(String value) {
            addCriterion("FABRIC_NAME not like", value, "fabricName");
            return this;
        }

        public Criteria andFabricNameIn(List values) {
            addCriterion("FABRIC_NAME in", values, "fabricName");
            return this;
        }

        public Criteria andFabricNameNotIn(List values) {
            addCriterion("FABRIC_NAME not in", values, "fabricName");
            return this;
        }

        public Criteria andFabricNameBetween(String value1, String value2) {
            addCriterion("FABRIC_NAME between", value1, value2, "fabricName");
            return this;
        }

        public Criteria andFabricNameNotBetween(String value1, String value2) {
            addCriterion("FABRIC_NAME not between", value1, value2, "fabricName");
            return this;
        }

        public Criteria andFabricColorIsNull() {
            addCriterion("FABRIC_COLOR is null");
            return this;
        }

        public Criteria andFabricColorIsNotNull() {
            addCriterion("FABRIC_COLOR is not null");
            return this;
        }

        public Criteria andFabricColorEqualTo(String value) {
            addCriterion("FABRIC_COLOR =", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorNotEqualTo(String value) {
            addCriterion("FABRIC_COLOR <>", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorGreaterThan(String value) {
            addCriterion("FABRIC_COLOR >", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorGreaterThanOrEqualTo(String value) {
            addCriterion("FABRIC_COLOR >=", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorLessThan(String value) {
            addCriterion("FABRIC_COLOR <", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorLessThanOrEqualTo(String value) {
            addCriterion("FABRIC_COLOR <=", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorLike(String value) {
            addCriterion("FABRIC_COLOR like", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorNotLike(String value) {
            addCriterion("FABRIC_COLOR not like", value, "fabricColor");
            return this;
        }

        public Criteria andFabricColorIn(List values) {
            addCriterion("FABRIC_COLOR in", values, "fabricColor");
            return this;
        }

        public Criteria andFabricColorNotIn(List values) {
            addCriterion("FABRIC_COLOR not in", values, "fabricColor");
            return this;
        }

        public Criteria andFabricColorBetween(String value1, String value2) {
            addCriterion("FABRIC_COLOR between", value1, value2, "fabricColor");
            return this;
        }

        public Criteria andFabricColorNotBetween(String value1, String value2) {
            addCriterion("FABRIC_COLOR not between", value1, value2, "fabricColor");
            return this;
        }

        public Criteria andFabricImgSnIsNull() {
            addCriterion("FABRIC_IMG_SN is null");
            return this;
        }

        public Criteria andFabricImgSnIsNotNull() {
            addCriterion("FABRIC_IMG_SN is not null");
            return this;
        }

        public Criteria andFabricImgSnEqualTo(Long value) {
            addCriterion("FABRIC_IMG_SN =", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnNotEqualTo(Long value) {
            addCriterion("FABRIC_IMG_SN <>", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnGreaterThan(Long value) {
            addCriterion("FABRIC_IMG_SN >", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnGreaterThanOrEqualTo(Long value) {
            addCriterion("FABRIC_IMG_SN >=", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnLessThan(Long value) {
            addCriterion("FABRIC_IMG_SN <", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnLessThanOrEqualTo(Long value) {
            addCriterion("FABRIC_IMG_SN <=", value, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnIn(List values) {
            addCriterion("FABRIC_IMG_SN in", values, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnNotIn(List values) {
            addCriterion("FABRIC_IMG_SN not in", values, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnBetween(Long value1, Long value2) {
            addCriterion("FABRIC_IMG_SN between", value1, value2, "fabricImgSn");
            return this;
        }

        public Criteria andFabricImgSnNotBetween(Long value1, Long value2) {
            addCriterion("FABRIC_IMG_SN not between", value1, value2, "fabricImgSn");
            return this;
        }

        public Criteria andColorIsNull() {
            addCriterion("COLOR is null");
            return this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("COLOR is not null");
            return this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("COLOR =", value, "color");
            return this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("COLOR <>", value, "color");
            return this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("COLOR >", value, "color");
            return this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("COLOR >=", value, "color");
            return this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("COLOR <", value, "color");
            return this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("COLOR <=", value, "color");
            return this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("COLOR like", value, "color");
            return this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("COLOR not like", value, "color");
            return this;
        }

        public Criteria andColorIn(List values) {
            addCriterion("COLOR in", values, "color");
            return this;
        }

        public Criteria andColorNotIn(List values) {
            addCriterion("COLOR not in", values, "color");
            return this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("COLOR between", value1, value2, "color");
            return this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("COLOR not between", value1, value2, "color");
            return this;
        }

        public Criteria andModelIsNull() {
            addCriterion("MODEL is null");
            return this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("MODEL is not null");
            return this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("MODEL =", value, "model");
            return this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("MODEL <>", value, "model");
            return this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("MODEL >", value, "model");
            return this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("MODEL >=", value, "model");
            return this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("MODEL <", value, "model");
            return this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("MODEL <=", value, "model");
            return this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("MODEL like", value, "model");
            return this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("MODEL not like", value, "model");
            return this;
        }

        public Criteria andModelIn(List values) {
            addCriterion("MODEL in", values, "model");
            return this;
        }

        public Criteria andModelNotIn(List values) {
            addCriterion("MODEL not in", values, "model");
            return this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("MODEL between", value1, value2, "model");
            return this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("MODEL not between", value1, value2, "model");
            return this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("CAPACITY is null");
            return this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("CAPACITY is not null");
            return this;
        }

        public Criteria andCapacityEqualTo(String value) {
            addCriterion("CAPACITY =", value, "capacity");
            return this;
        }

        public Criteria andCapacityNotEqualTo(String value) {
            addCriterion("CAPACITY <>", value, "capacity");
            return this;
        }

        public Criteria andCapacityGreaterThan(String value) {
            addCriterion("CAPACITY >", value, "capacity");
            return this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(String value) {
            addCriterion("CAPACITY >=", value, "capacity");
            return this;
        }

        public Criteria andCapacityLessThan(String value) {
            addCriterion("CAPACITY <", value, "capacity");
            return this;
        }

        public Criteria andCapacityLessThanOrEqualTo(String value) {
            addCriterion("CAPACITY <=", value, "capacity");
            return this;
        }

        public Criteria andCapacityLike(String value) {
            addCriterion("CAPACITY like", value, "capacity");
            return this;
        }

        public Criteria andCapacityNotLike(String value) {
            addCriterion("CAPACITY not like", value, "capacity");
            return this;
        }

        public Criteria andCapacityIn(List values) {
            addCriterion("CAPACITY in", values, "capacity");
            return this;
        }

        public Criteria andCapacityNotIn(List values) {
            addCriterion("CAPACITY not in", values, "capacity");
            return this;
        }

        public Criteria andCapacityBetween(String value1, String value2) {
            addCriterion("CAPACITY between", value1, value2, "capacity");
            return this;
        }

        public Criteria andCapacityNotBetween(String value1, String value2) {
            addCriterion("CAPACITY not between", value1, value2, "capacity");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }

        public Criteria andAdderNameIsNull() {
            addCriterion("ADDER_NAME is null");
            return this;
        }

        public Criteria andAdderNameIsNotNull() {
            addCriterion("ADDER_NAME is not null");
            return this;
        }

        public Criteria andAdderNameEqualTo(String value) {
            addCriterion("ADDER_NAME =", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotEqualTo(String value) {
            addCriterion("ADDER_NAME <>", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThan(String value) {
            addCriterion("ADDER_NAME >", value, "adderName");
            return this;
        }

        public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME >=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThan(String value) {
            addCriterion("ADDER_NAME <", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLessThanOrEqualTo(String value) {
            addCriterion("ADDER_NAME <=", value, "adderName");
            return this;
        }

        public Criteria andAdderNameLike(String value) {
            addCriterion("ADDER_NAME like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameNotLike(String value) {
            addCriterion("ADDER_NAME not like", value, "adderName");
            return this;
        }

        public Criteria andAdderNameIn(List values) {
            addCriterion("ADDER_NAME in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameNotIn(List values) {
            addCriterion("ADDER_NAME not in", values, "adderName");
            return this;
        }

        public Criteria andAdderNameBetween(String value1, String value2) {
            addCriterion("ADDER_NAME between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAdderNameNotBetween(String value1, String value2) {
            addCriterion("ADDER_NAME not between", value1, value2, "adderName");
            return this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return this;
        }

        public Criteria andAddTimeIn(List values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeNotIn(List values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return this;
        }

        public Criteria andUpdaterSnIsNull() {
            addCriterion("UPDATER_SN is null");
            return this;
        }

        public Criteria andUpdaterSnIsNotNull() {
            addCriterion("UPDATER_SN is not null");
            return this;
        }

        public Criteria andUpdaterSnEqualTo(Long value) {
            addCriterion("UPDATER_SN =", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotEqualTo(Long value) {
            addCriterion("UPDATER_SN <>", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThan(Long value) {
            addCriterion("UPDATER_SN >", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN >=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThan(Long value) {
            addCriterion("UPDATER_SN <", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnLessThanOrEqualTo(Long value) {
            addCriterion("UPDATER_SN <=", value, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnIn(List values) {
            addCriterion("UPDATER_SN in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotIn(List values) {
            addCriterion("UPDATER_SN not in", values, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterSnNotBetween(Long value1, Long value2) {
            addCriterion("UPDATER_SN not between", value1, value2, "updaterSn");
            return this;
        }

        public Criteria andUpdaterNameIsNull() {
            addCriterion("UPDATER_NAME is null");
            return this;
        }

        public Criteria andUpdaterNameIsNotNull() {
            addCriterion("UPDATER_NAME is not null");
            return this;
        }

        public Criteria andUpdaterNameEqualTo(String value) {
            addCriterion("UPDATER_NAME =", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotEqualTo(String value) {
            addCriterion("UPDATER_NAME <>", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThan(String value) {
            addCriterion("UPDATER_NAME >", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME >=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThan(String value) {
            addCriterion("UPDATER_NAME <", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATER_NAME <=", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameLike(String value) {
            addCriterion("UPDATER_NAME like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotLike(String value) {
            addCriterion("UPDATER_NAME not like", value, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameIn(List values) {
            addCriterion("UPDATER_NAME in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotIn(List values) {
            addCriterion("UPDATER_NAME not in", values, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdaterNameNotBetween(String value1, String value2) {
            addCriterion("UPDATER_NAME not between", value1, value2, "updaterName");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andWorkmanshipIsNull() {
            addCriterion("workmanship is null");
            return this;
        }

        public Criteria andWorkmanshipIsNotNull() {
            addCriterion("workmanship is not null");
            return this;
        }

        public Criteria andWorkmanshipEqualTo(String value) {
            addCriterion("workmanship =", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipNotEqualTo(String value) {
            addCriterion("workmanship <>", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipGreaterThan(String value) {
            addCriterion("workmanship >", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipGreaterThanOrEqualTo(String value) {
            addCriterion("workmanship >=", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipLessThan(String value) {
            addCriterion("workmanship <", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipLessThanOrEqualTo(String value) {
            addCriterion("workmanship <=", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipLike(String value) {
            addCriterion("workmanship like", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipNotLike(String value) {
            addCriterion("workmanship not like", value, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipIn(List values) {
            addCriterion("workmanship in", values, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipNotIn(List values) {
            addCriterion("workmanship not in", values, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipBetween(String value1, String value2) {
            addCriterion("workmanship between", value1, value2, "workmanship");
            return this;
        }

        public Criteria andWorkmanshipNotBetween(String value1, String value2) {
            addCriterion("workmanship not between", value1, value2, "workmanship");
            return this;
        }

        public Criteria andLrIsNull() {
            addCriterion("lr is null");
            return this;
        }

        public Criteria andLrIsNotNull() {
            addCriterion("lr is not null");
            return this;
        }

        public Criteria andLrEqualTo(String value) {
            addCriterion("lr =", value, "lr");
            return this;
        }

        public Criteria andLrNotEqualTo(String value) {
            addCriterion("lr <>", value, "lr");
            return this;
        }

        public Criteria andLrGreaterThan(String value) {
            addCriterion("lr >", value, "lr");
            return this;
        }

        public Criteria andLrGreaterThanOrEqualTo(String value) {
            addCriterion("lr >=", value, "lr");
            return this;
        }

        public Criteria andLrLessThan(String value) {
            addCriterion("lr <", value, "lr");
            return this;
        }

        public Criteria andLrLessThanOrEqualTo(String value) {
            addCriterion("lr <=", value, "lr");
            return this;
        }

        public Criteria andLrLike(String value) {
            addCriterion("lr like", value, "lr");
            return this;
        }

        public Criteria andLrNotLike(String value) {
            addCriterion("lr not like", value, "lr");
            return this;
        }

        public Criteria andLrIn(List values) {
            addCriterion("lr in", values, "lr");
            return this;
        }

        public Criteria andLrNotIn(List values) {
            addCriterion("lr not in", values, "lr");
            return this;
        }

        public Criteria andLrBetween(String value1, String value2) {
            addCriterion("lr between", value1, value2, "lr");
            return this;
        }

        public Criteria andLrNotBetween(String value1, String value2) {
            addCriterion("lr not between", value1, value2, "lr");
            return this;
        }

        public Criteria andLrRoundIsNull() {
            addCriterion("lr_round is null");
            return this;
        }

        public Criteria andLrRoundIsNotNull() {
            addCriterion("lr_round is not null");
            return this;
        }

        public Criteria andLrRoundEqualTo(String value) {
            addCriterion("lr_round =", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundNotEqualTo(String value) {
            addCriterion("lr_round <>", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundGreaterThan(String value) {
            addCriterion("lr_round >", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundGreaterThanOrEqualTo(String value) {
            addCriterion("lr_round >=", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundLessThan(String value) {
            addCriterion("lr_round <", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundLessThanOrEqualTo(String value) {
            addCriterion("lr_round <=", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundLike(String value) {
            addCriterion("lr_round like", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundNotLike(String value) {
            addCriterion("lr_round not like", value, "lrRound");
            return this;
        }

        public Criteria andLrRoundIn(List values) {
            addCriterion("lr_round in", values, "lrRound");
            return this;
        }

        public Criteria andLrRoundNotIn(List values) {
            addCriterion("lr_round not in", values, "lrRound");
            return this;
        }

        public Criteria andLrRoundBetween(String value1, String value2) {
            addCriterion("lr_round between", value1, value2, "lrRound");
            return this;
        }

        public Criteria andLrRoundNotBetween(String value1, String value2) {
            addCriterion("lr_round not between", value1, value2, "lrRound");
            return this;
        }

        public Criteria andVendernameIsNull() {
            addCriterion("vendername is null");
            return this;
        }

        public Criteria andVendernameIsNotNull() {
            addCriterion("vendername is not null");
            return this;
        }

        public Criteria andVendernameEqualTo(String value) {
            addCriterion("vendername =", value, "vendername");
            return this;
        }

        public Criteria andVendernameNotEqualTo(String value) {
            addCriterion("vendername <>", value, "vendername");
            return this;
        }

        public Criteria andVendernameGreaterThan(String value) {
            addCriterion("vendername >", value, "vendername");
            return this;
        }

        public Criteria andVendernameGreaterThanOrEqualTo(String value) {
            addCriterion("vendername >=", value, "vendername");
            return this;
        }

        public Criteria andVendernameLessThan(String value) {
            addCriterion("vendername <", value, "vendername");
            return this;
        }

        public Criteria andVendernameLessThanOrEqualTo(String value) {
            addCriterion("vendername <=", value, "vendername");
            return this;
        }

        public Criteria andVendernameLike(String value) {
            addCriterion("vendername like", value, "vendername");
            return this;
        }

        public Criteria andVendernameNotLike(String value) {
            addCriterion("vendername not like", value, "vendername");
            return this;
        }

        public Criteria andVendernameIn(List values) {
            addCriterion("vendername in", values, "vendername");
            return this;
        }

        public Criteria andVendernameNotIn(List values) {
            addCriterion("vendername not in", values, "vendername");
            return this;
        }

        public Criteria andVendernameBetween(String value1, String value2) {
            addCriterion("vendername between", value1, value2, "vendername");
            return this;
        }

        public Criteria andVendernameNotBetween(String value1, String value2) {
            addCriterion("vendername not between", value1, value2, "vendername");
            return this;
        }

        public Criteria andDimensionIsNull() {
            addCriterion("dimension is null");
            return this;
        }

        public Criteria andDimensionIsNotNull() {
            addCriterion("dimension is not null");
            return this;
        }

        public Criteria andDimensionEqualTo(String value) {
            addCriterion("dimension =", value, "dimension");
            return this;
        }

        public Criteria andDimensionNotEqualTo(String value) {
            addCriterion("dimension <>", value, "dimension");
            return this;
        }

        public Criteria andDimensionGreaterThan(String value) {
            addCriterion("dimension >", value, "dimension");
            return this;
        }

        public Criteria andDimensionGreaterThanOrEqualTo(String value) {
            addCriterion("dimension >=", value, "dimension");
            return this;
        }

        public Criteria andDimensionLessThan(String value) {
            addCriterion("dimension <", value, "dimension");
            return this;
        }

        public Criteria andDimensionLessThanOrEqualTo(String value) {
            addCriterion("dimension <=", value, "dimension");
            return this;
        }

        public Criteria andDimensionLike(String value) {
            addCriterion("dimension like", value, "dimension");
            return this;
        }

        public Criteria andDimensionNotLike(String value) {
            addCriterion("dimension not like", value, "dimension");
            return this;
        }

        public Criteria andDimensionIn(List values) {
            addCriterion("dimension in", values, "dimension");
            return this;
        }

        public Criteria andDimensionNotIn(List values) {
            addCriterion("dimension not in", values, "dimension");
            return this;
        }

        public Criteria andDimensionBetween(String value1, String value2) {
            addCriterion("dimension between", value1, value2, "dimension");
            return this;
        }

        public Criteria andDimensionNotBetween(String value1, String value2) {
            addCriterion("dimension not between", value1, value2, "dimension");
            return this;
        }

        public Criteria andAdderSnIsNull() {
            addCriterion("ADDER_SN is null");
            return this;
        }

        public Criteria andAdderSnIsNotNull() {
            addCriterion("ADDER_SN is not null");
            return this;
        }

        public Criteria andAdderSnEqualTo(Long value) {
            addCriterion("ADDER_SN =", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotEqualTo(Long value) {
            addCriterion("ADDER_SN <>", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThan(Long value) {
            addCriterion("ADDER_SN >", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnGreaterThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN >=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThan(Long value) {
            addCriterion("ADDER_SN <", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnLessThanOrEqualTo(Long value) {
            addCriterion("ADDER_SN <=", value, "adderSn");
            return this;
        }

        public Criteria andAdderSnIn(List values) {
            addCriterion("ADDER_SN in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotIn(List values) {
            addCriterion("ADDER_SN not in", values, "adderSn");
            return this;
        }

        public Criteria andAdderSnBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN between", value1, value2, "adderSn");
            return this;
        }

        public Criteria andAdderSnNotBetween(Long value1, Long value2) {
            addCriterion("ADDER_SN not between", value1, value2, "adderSn");
            return this;
        }
    }
}